version = "3.8.3"
runner.dialect = scala3

maxColumn = 100
align.preset = some
docstrings.style = Asterisk
newlines.beforeCurlyLambdaParams = multilineWithCaseOnly
rewrite.rules = [RedundantBraces, RedundantParens, SortModifiers]
