pages = [{"l":"index.html#","e":false,"i":"","n":"marola-cli","t":"marola-cli","d":"","k":"static","x":""},
{"l":"marola.html#","e":false,"i":"","n":"marola","t":"marola","d":"","k":"package","x":""},
{"l":"marola/agent.html#","e":false,"i":"","n":"marola.agent","t":"marola.agent","d":"","k":"package","x":""},
{"l":"marola/agent/ChatServer$.html#","e":false,"i":"","n":"ChatServer","t":"ChatServer","d":"marola.agent","k":"object","x":""},
{"l":"marola/agent/ChatServer$.html#DefaultPort-0","e":false,"i":"","n":"DefaultPort","t":"DefaultPort: Int","d":"marola.agent.ChatServer","k":"val","x":""},
{"l":"marola/agent/ChatServer$.html#responseFor-946","e":false,"i":"","n":"responseFor","t":"responseFor(question: String, store: KnowledgeStore, llm: Option[LlmClient]): JsonValue < Sync","d":"marola.agent.ChatServer","k":"def","x":""},
{"l":"marola/agent/ChatServer$.html#start-fffffc62","e":false,"i":"","n":"start","t":"start(config: AppConfig, port: Int = ...): HttpServer","d":"marola.agent.ChatServer","k":"def","x":""},
{"l":"marola/agent/SwimConditionsMcpServer$.html#","e":false,"i":"","n":"SwimConditionsMcpServer","t":"SwimConditionsMcpServer","d":"marola.agent","k":"object","x":""},
{"l":"marola/agent/SwimConditionsMcpServer$.html#main-913","e":false,"i":"","n":"main","t":"main(args: Array[String]): Unit","d":"marola.agent.SwimConditionsMcpServer","k":"def","x":""},
{"l":"marola/bench.html#","e":false,"i":"","n":"marola.bench","t":"marola.bench","d":"","k":"package","x":""},
{"l":"marola/bench/BenchmarkLedger$.html#","e":false,"i":"","n":"BenchmarkLedger","t":"BenchmarkLedger","d":"marola.bench","k":"object","x":""},
{"l":"marola/bench/BenchmarkLedger$.html#corpusSha-fffff3b6","e":false,"i":"","n":"corpusSha","t":"corpusSha(dir: Path): String","d":"marola.bench.BenchmarkLedger","k":"def","x":""},
{"l":"marola/bench/BenchmarkLedger$.html#gitSha-fffff3b6","e":false,"i":"","n":"gitSha","t":"gitSha(dir: Path = ...): String","d":"marola.bench.BenchmarkLedger","k":"def","x":""},
{"l":"marola/bench/BenchmarkLedger$.html#log-fffff942","e":false,"i":"","n":"log","t":"log(ledger: RunLedger, experimentPrefix: String, report: Report, context: Context, reportPath: Path): Option[RunHandle] < Sync","d":"marola.bench.BenchmarkLedger","k":"def","x":""},
{"l":"marola/bench/BenchmarkLedger$.html#metrics-fffff76b","e":false,"i":"","n":"metrics","t":"metrics(report: Report): Map[String, Double]","d":"marola.bench.BenchmarkLedger","k":"def","x":""},
{"l":"marola/bench/BenchmarkLedger$.html#params-fffffaca","e":false,"i":"","n":"params","t":"params(report: Report, context: Context): Map[String, String]","d":"marola.bench.BenchmarkLedger","k":"def","x":""},
{"l":"marola/bench/BenchmarkLedger$.html#runName-fffff3b6","e":false,"i":"","n":"runName","t":"runName(reportPath: Path): String","d":"marola.bench.BenchmarkLedger","k":"def","x":""},
{"l":"marola/bench/BenchmarkLedger$$Context.html#","e":false,"i":"","n":"Context","t":"Context(model: String, embedModel: String, minScore: Double, corpusSha: String, gitSha: String)","d":"marola.bench.BenchmarkLedger","k":"class","x":""},
{"l":"marola/bench/OceanBenchmark$.html#","e":false,"i":"","n":"OceanBenchmark","t":"OceanBenchmark","d":"marola.bench","k":"object","x":""},
{"l":"marola/bench/OceanBenchmark$.html#Arms-0","e":false,"i":"","n":"Arms","t":"Arms: List[String]","d":"marola.bench.OceanBenchmark","k":"val","x":""},
{"l":"marola/bench/OceanBenchmark$.html#coverage-766","e":false,"i":"","n":"coverage","t":"coverage(answer: String, keywords: List[String]): Double","d":"marola.bench.OceanBenchmark","k":"def","x":""},
{"l":"marola/bench/OceanBenchmark$.html#isAbstained-fffffd1b","e":false,"i":"","n":"isAbstained","t":"isAbstained(answer: String): Boolean","d":"marola.bench.OceanBenchmark","k":"def","x":""},
{"l":"marola/bench/OceanBenchmark$.html#isCited-fffffd1b","e":false,"i":"","n":"isCited","t":"isCited(answer: String): Boolean","d":"marola.bench.OceanBenchmark","k":"def","x":""},
{"l":"marola/bench/OceanBenchmark$.html#load-fffffc52","e":false,"i":"","n":"load","t":"load(): List[Question]","d":"marola.bench.OceanBenchmark","k":"def","x":""},
{"l":"marola/bench/OceanBenchmark$.html#render-c25","e":false,"i":"","n":"render","t":"render(results: List[Result], summaries: List[ArmSummary]): String","d":"marola.bench.OceanBenchmark","k":"def","x":""},
{"l":"marola/bench/OceanBenchmark$.html#run-fffff176","e":false,"i":"","n":"run","t":"run(store: KnowledgeStore, llm: LlmClient, minScore: Double): Report < Sync","d":"marola.bench.OceanBenchmark","k":"def","x":""},
{"l":"marola/bench/OceanBenchmark$.html#save-fffffbe8","e":false,"i":"","n":"save","t":"save(report: Report): String","d":"marola.bench.OceanBenchmark","k":"def","x":""},
{"l":"marola/bench/OceanBenchmark$.html#summarise-68c","e":false,"i":"","n":"summarise","t":"summarise(arm: String, rs: List[Result]): ArmSummary","d":"marola.bench.OceanBenchmark","k":"def","x":""},
{"l":"marola/bench/OceanBenchmark$.html#verdict-c25","e":false,"i":"","n":"verdict","t":"verdict(summaries: List[ArmSummary], results: List[Result]): String","d":"marola.bench.OceanBenchmark","k":"def","x":""},
{"l":"marola/bench/OceanBenchmark$$ArmSummary.html#","e":false,"i":"","n":"ArmSummary","t":"ArmSummary(arm: String, coverageInCorpus: Double, coverageGeneral: Double, coverageAll: Double, citedPct: Double, abstainedPct: Double, meanMs: Long)","d":"marola.bench.OceanBenchmark","k":"class","x":""},
{"l":"marola/bench/OceanBenchmark$$Question.html#","e":false,"i":"","n":"Question","t":"Question(id: String, topic: String, question: String, keywords: List[String], inCorpus: Boolean)","d":"marola.bench.OceanBenchmark","k":"class","x":""},
{"l":"marola/bench/OceanBenchmark$$Report.html#","e":false,"i":"","n":"Report","t":"Report(model: String, results: List[Result], summaries: List[ArmSummary], markdown: String)","d":"marola.bench.OceanBenchmark","k":"class","x":""},
{"l":"marola/bench/OceanBenchmark$$Result.html#","e":false,"i":"","n":"Result","t":"Result(arm: String, q: Question, answer: String, coverage: Double, cited: Boolean, abstained: Boolean, ms: Long)","d":"marola.bench.OceanBenchmark","k":"class","x":""},
{"l":"marola/site.html#","e":false,"i":"","n":"marola.site","t":"marola.site","d":"","k":"package","x":""},
{"l":"marola/site/SiteBuilder$.html#","e":false,"i":"","n":"SiteBuilder","t":"SiteBuilder","d":"marola.site","k":"object","x":""},
{"l":"marola/site/SiteBuilder$.html#DefaultOut-0","e":false,"i":"","n":"DefaultOut","t":"DefaultOut: Path","d":"marola.site.SiteBuilder","k":"val","x":""},
{"l":"marola/site/SiteBuilder$.html#build-fffff441","e":false,"i":"","n":"build","t":"build(areas: List[Area], out: Path, water: Coordinates => Option[WaterQualityClient], now: OffsetDateTime, accessibility: Option[AccessibilityClient] = ...): List[Path] < Sync","d":"marola.site.SiteBuilder","k":"def","x":""},
{"l":"marola/site/SiteBuilder$$Area.html#","e":false,"i":"","n":"Area","t":"Area(id: String, name: String, lat: Double, lon: Double, radiusKm: Double, beachLimit: Int, zone: ZoneId, tiles: String, tilesAttribution: String)","d":"marola.site.SiteBuilder","k":"class","x":""},
{"l":"marola/site/SiteBuilder$$Area.html#origin-0","e":false,"i":"","n":"origin","t":"origin: Coordinates","d":"marola.site.SiteBuilder.Area","k":"def","x":""},
{"l":"marola/site/SiteBuilder$$Areas$.html#","e":false,"i":"","n":"Areas","t":"Areas","d":"marola.site.SiteBuilder","k":"object","x":""},
{"l":"marola/site/SiteBuilder$$Areas$.html#DefaultPath-0","e":false,"i":"","n":"DefaultPath","t":"DefaultPath: Path","d":"marola.site.SiteBuilder.Areas","k":"val","x":""},
{"l":"marola/site/SiteBuilder$$Areas$.html#load-fffff2e1","e":false,"i":"","n":"load","t":"load(path: Path): List[Area]","d":"marola.site.SiteBuilder.Areas","k":"def","x":""},
{"l":"marola/site/SiteBuilder$$Areas$.html#parse-94d","e":false,"i":"","n":"parse","t":"parse(jsonText: String): List[Area]","d":"marola.site.SiteBuilder.Areas","k":"def","x":""},
{"l":"marola/AppConfig.html#","e":false,"i":"","n":"AppConfig","t":"AppConfig(telegramBotToken: Option[String], beachSearchRadiusKm: Double, originLat: Option[Double], originLon: Option[Double], waterQualityProvider: WaterProvider, facilitiesProvider: FacilitiesProvider, localEmbedModel: String, knowledgeDir: String, knowledgeIndexPath: String, seaLoreEnabled: Boolean, askFallback: Fallback, askMinScore: Double, localLlmBaseUrl: String, localLlmModel: String, localSightingStorePath: String, localVisionModel: String, mlflowTrackingUri: Option[String], mlflowExperiment: String, tracesBackend: TraceBackend, traceContent: Boolean, waterCacheDir: Path = ...)","d":"marola","k":"class","x":""},
{"l":"marola/AppConfig.html#accessibilityClient-0","e":false,"i":"","n":"accessibilityClient","t":"accessibilityClient: AccessibilityClient","d":"marola.AppConfig","k":"def","x":""},
{"l":"marola/AppConfig.html#knowledgeStore-0","e":false,"i":"","n":"knowledgeStore","t":"knowledgeStore: FileKnowledgeStore","d":"marola.AppConfig","k":"def","x":""},
{"l":"marola/AppConfig.html#llmClient-0","e":false,"i":"","n":"llmClient","t":"llmClient: LlmClient","d":"marola.AppConfig","k":"def","x":""},
{"l":"marola/AppConfig.html#origin-0","e":false,"i":"","n":"origin","t":"origin: Option[Coordinates]","d":"marola.AppConfig","k":"def","x":""},
{"l":"marola/AppConfig.html#redacted-0","e":false,"i":"","n":"redacted","t":"redacted: String","d":"marola.AppConfig","k":"def","x":""},
{"l":"marola/AppConfig.html#runLedger-0","e":false,"i":"","n":"runLedger","t":"runLedger: RunLedger","d":"marola.AppConfig","k":"def","x":""},
{"l":"marola/AppConfig.html#sightingStore-0","e":false,"i":"","n":"sightingStore","t":"sightingStore: SightingStore","d":"marola.AppConfig","k":"def","x":""},
{"l":"marola/AppConfig.html#tracedLlmClient-ffffff3c","e":false,"i":"","n":"tracedLlmClient","t":"tracedLlmClient(tracing: Tracing): LlmClient","d":"marola.AppConfig","k":"def","x":""},
{"l":"marola/AppConfig.html#tracing-0","e":false,"i":"","n":"tracing","t":"tracing: Tracing < Sync","d":"marola.AppConfig","k":"def","x":""},
{"l":"marola/AppConfig.html#visionClient-0","e":false,"i":"","n":"visionClient","t":"visionClient: VisionClient","d":"marola.AppConfig","k":"def","x":""},
{"l":"marola/AppConfig.html#waterQualityClient-ffffffeb","e":false,"i":"","n":"waterQualityClient","t":"waterQualityClient(origin: Coordinates): Option[WaterQualityClient]","d":"marola.AppConfig","k":"def","x":""},
{"l":"marola/AppConfig$.html#","e":false,"i":"","n":"AppConfig","t":"AppConfig","d":"marola","k":"object","x":""},
{"l":"marola/AppConfig$.html#fromEnv-0","e":false,"i":"","n":"fromEnv","t":"fromEnv: AppConfig","d":"marola.AppConfig","k":"def","x":""},
{"l":"marola/FacilitiesProvider$.html#","e":false,"i":"","n":"FacilitiesProvider","t":"FacilitiesProvider","d":"marola","k":"object","x":""},
{"l":"marola/FacilitiesProvider$.html#derived$CanEqual-0","e":false,"i":"","n":"derived$CanEqual","t":"derived$CanEqual: CanEqual[FacilitiesProvider, FacilitiesProvider]","d":"marola.FacilitiesProvider","k":"given","x":""},
{"l":"marola/FacilitiesProvider$.html#fromEnv-fffff2fd","e":false,"i":"","n":"fromEnv","t":"fromEnv(value: Option[String]): FacilitiesProvider","d":"marola.FacilitiesProvider","k":"def","x":""},
{"l":"marola/FacilitiesProvider.html#","e":false,"i":"","n":"FacilitiesProvider","t":"FacilitiesProvider","d":"marola","k":"enum","x":""},
{"l":"marola/FacilitiesProvider.html#Overpass-0","e":false,"i":"","n":"Overpass","t":"Overpass extends FacilitiesProvider","d":"marola.FacilitiesProvider","k":"val","x":""},
{"l":"marola/FacilitiesProvider.html#Off-0","e":false,"i":"","n":"Off","t":"Off extends FacilitiesProvider","d":"marola.FacilitiesProvider","k":"val","x":""},
{"l":"marola/Main$.html#","e":false,"i":"","n":"Main","t":"Main extends KyoApp","d":"marola","k":"object","x":""},
{"l":"marola/Main$.html#handleWithInterrupts-dbc","e":false,"i":"","n":"handleWithInterrupts","t":"handleWithInterrupts[A](v: A < (Async & Abort[Throwable]))(using Frame): A < (Async & Abort[Throwable])","d":"marola.Main","k":"def","x":""},
{"l":"marola/Report$.html#","e":false,"i":"","n":"Report","t":"Report","d":"marola","k":"object","x":""},
{"l":"marola/Report$.html#answer-383","e":false,"i":"","n":"answer","t":"answer(a: Answer): String","d":"marola.Report","k":"def","x":""},
{"l":"marola/Report$.html#briefLine-7b3","e":false,"i":"","n":"briefLine","t":"briefLine(rank: Int, best: BestHour): String","d":"marola.Report","k":"def","x":""},
{"l":"marola/Report$.html#compass-dfe","e":false,"i":"","n":"compass","t":"compass(deg: Double): String","d":"marola.Report","k":"def","x":""},
{"l":"marola/Report$.html#detail-a7a","e":false,"i":"","n":"detail","t":"detail(best: BestHour): String","d":"marola.Report","k":"def","x":""},
{"l":"marola/Report$.html#facilitiesLine-ffffff83","e":false,"i":"","n":"facilitiesLine","t":"facilitiesLine(f: Facilities): Option[String]","d":"marola.Report","k":"def","x":""},
{"l":"marola/Report$.html#line-7b3","e":false,"i":"","n":"line","t":"line(rank: Int, best: BestHour): String","d":"marola.Report","k":"def","x":""},
{"l":"marola/Report$.html#lore-2d4","e":false,"i":"","n":"lore","t":"lore(today: LocalDate, beachName: String, origin: Coordinates): Option[String]","d":"marola.Report","k":"def","x":""},
{"l":"marola/Report$.html#nearestTrail-40a","e":false,"i":"","n":"nearestTrail","t":"nearestTrail(beachName: String, trails: List[Trail]): Option[Trail]","d":"marola.Report","k":"def","x":""},
{"l":"marola/Report$.html#todayFor-fffffccf","e":false,"i":"","n":"todayFor","t":"todayFor(best: BestHour): LocalDate","d":"marola.Report","k":"def","x":""},
{"l":"marola/Report$.html#trailsLine-2a2","e":false,"i":"","n":"trailsLine","t":"trailsLine(trail: Option[Trail]): String","d":"marola.Report","k":"def","x":""},
{"l":"marola/Report$.html#waterSummary-a7a","e":false,"i":"","n":"waterSummary","t":"waterSummary(best: BestHour): String","d":"marola.Report","k":"def","x":""},
{"l":"marola/TraceBackend$.html#","e":false,"i":"","n":"TraceBackend","t":"TraceBackend","d":"marola","k":"object","x":""},
{"l":"marola/TraceBackend$.html#derived$CanEqual-0","e":false,"i":"","n":"derived$CanEqual","t":"derived$CanEqual: CanEqual[TraceBackend, TraceBackend]","d":"marola.TraceBackend","k":"given","x":""},
{"l":"marola/TraceBackend$.html#fromEnv-fffff93a","e":false,"i":"","n":"fromEnv","t":"fromEnv(value: Option[String]): TraceBackend","d":"marola.TraceBackend","k":"def","x":""},
{"l":"marola/TraceBackend.html#","e":false,"i":"","n":"TraceBackend","t":"TraceBackend","d":"marola","k":"enum","x":""},
{"l":"marola/TraceBackend.html#Off-0","e":false,"i":"","n":"Off","t":"Off extends TraceBackend","d":"marola.TraceBackend","k":"val","x":""},
{"l":"marola/TraceBackend.html#Mlflow-0","e":false,"i":"","n":"Mlflow","t":"Mlflow extends TraceBackend","d":"marola.TraceBackend","k":"val","x":""},
{"l":"marola/WaterProvider.html#","e":false,"i":"","n":"WaterProvider","t":"WaterProvider","d":"marola","k":"enum","x":""},
{"l":"marola/WaterProvider.html#Auto-0","e":false,"i":"","n":"Auto","t":"Auto extends WaterProvider","d":"marola.WaterProvider","k":"val","x":""},
{"l":"marola/WaterProvider.html#ImaSc-0","e":false,"i":"","n":"ImaSc","t":"ImaSc extends WaterProvider","d":"marola.WaterProvider","k":"val","x":""},
{"l":"marola/WaterProvider.html#InemaBa-0","e":false,"i":"","n":"InemaBa","t":"InemaBa extends WaterProvider","d":"marola.WaterProvider","k":"val","x":""},
{"l":"marola/WaterProvider.html#IneaRj-0","e":false,"i":"","n":"IneaRj","t":"IneaRj extends WaterProvider","d":"marola.WaterProvider","k":"val","x":""},
{"l":"marola/WaterProvider.html#None-0","e":false,"i":"","n":"None","t":"None extends WaterProvider","d":"marola.WaterProvider","k":"val","x":""},
{"l":"marola/WaterProvider$.html#","e":false,"i":"","n":"WaterProvider","t":"WaterProvider","d":"marola","k":"object","x":""},
{"l":"marola/WaterProvider$.html#derived$CanEqual-0","e":false,"i":"","n":"derived$CanEqual","t":"derived$CanEqual: CanEqual[WaterProvider, WaterProvider]","d":"marola.WaterProvider","k":"given","x":""},
{"l":"marola/WaterProvider$.html#fromEnv-fffff9dd","e":false,"i":"","n":"fromEnv","t":"fromEnv(value: Option[String]): WaterProvider","d":"marola.WaterProvider","k":"def","x":""}];