pages = [{"l":"index.html#","e":false,"i":"","n":"marola-local","t":"marola-local","d":"","k":"static","x":""},
{"l":"marola.html#","e":false,"i":"","n":"marola","t":"marola","d":"","k":"package","x":""},
{"l":"marola/knowledge.html#","e":false,"i":"","n":"marola.knowledge","t":"marola.knowledge","d":"","k":"package","x":""},
{"l":"marola/knowledge/OllamaEmbedder$.html#","e":false,"i":"","n":"OllamaEmbedder","t":"OllamaEmbedder","d":"marola.knowledge","k":"object","x":""},
{"l":"marola/knowledge/OllamaEmbedder$.html#DefaultModel-0","e":false,"i":"","n":"DefaultModel","t":"DefaultModel: String","d":"marola.knowledge.OllamaEmbedder","k":"val","x":""},
{"l":"marola/knowledge/OllamaEmbedder$.html#nativeBaseUrl-fffff2ca","e":false,"i":"","n":"nativeBaseUrl","t":"nativeBaseUrl(openAiCompatibleBaseUrl: String): String","d":"marola.knowledge.OllamaEmbedder","k":"def","x":""},
{"l":"marola/knowledge/OllamaEmbedder.html#","e":false,"i":"","n":"OllamaEmbedder","t":"OllamaEmbedder(nativeBaseUrl: String, val model: String) extends Embedder","d":"marola.knowledge","k":"class","x":""},
{"l":"marola/knowledge/OllamaEmbedder.html#embed-fffff1e5","e":false,"i":"","n":"embed","t":"embed(texts: List[String]): List[Vector[Double]] < Sync","d":"marola.knowledge.OllamaEmbedder","k":"def","x":""},
{"l":"marola/knowledge/OllamaEmbedder.html#model-0","e":false,"i":"","n":"model","t":"model: String","d":"marola.knowledge.OllamaEmbedder","k":"val","x":""},
{"l":"marola/ledger.html#","e":false,"i":"","n":"marola.ledger","t":"marola.ledger","d":"","k":"package","x":""},
{"l":"marola/ledger/MlflowApi$.html#","e":false,"i":"","n":"MlflowApi","t":"MlflowApi","d":"marola.ledger","k":"object","x":""},
{"l":"marola/ledger/MlflowApi$.html#encode-fffff2ca","e":false,"i":"","n":"encode","t":"encode(s: String): String","d":"marola.ledger.MlflowApi","k":"def","x":""},
{"l":"marola/ledger/MlflowApi$.html#field-175","e":false,"i":"","n":"field","t":"field(json: JsonValue, key: String): String","d":"marola.ledger.MlflowApi","k":"def","x":""},
{"l":"marola/ledger/MlflowApi$.html#getOrCreateExperiment-fffff85d","e":false,"i":"","n":"getOrCreateExperiment","t":"getOrCreateExperiment(trackingUri: String, name: String): String < Sync","d":"marola.ledger.MlflowApi","k":"def","x":""},
{"l":"marola/ledger/MlflowApi$.html#restBase-fffff2ca","e":false,"i":"","n":"restBase","t":"restBase(trackingUri: String): String","d":"marola.ledger.MlflowApi","k":"def","x":""},
{"l":"marola/ledger/MlflowRunLedger.html#","e":false,"i":"","n":"MlflowRunLedger","t":"MlflowRunLedger(trackingUri: String, now: () => Long = ...) extends RunLedger","d":"marola.ledger","k":"class","x":""},
{"l":"marola/ledger/MlflowRunLedger.html#artifact-fffff6d6","e":false,"i":"","n":"artifact","t":"artifact(run: RunHandle, path: Path): Unit < Sync","d":"marola.ledger.MlflowRunLedger","k":"def","x":""},
{"l":"marola/ledger/MlflowRunLedger.html#end-fffff1c1","e":false,"i":"","n":"end","t":"end(run: RunHandle, ok: Boolean): Unit < Sync","d":"marola.ledger.MlflowRunLedger","k":"def","x":""},
{"l":"marola/ledger/MlflowRunLedger.html#metrics-ffffffe0","e":false,"i":"","n":"metrics","t":"metrics(run: RunHandle, values: Map[String, Double], step: Int = ...): Unit < Sync","d":"marola.ledger.MlflowRunLedger","k":"def","x":""},
{"l":"marola/ledger/MlflowRunLedger.html#start-fffffe05","e":false,"i":"","n":"start","t":"start(experiment: String, name: String, params: Map[String, String]): RunHandle < Sync","d":"marola.ledger.MlflowRunLedger","k":"def","x":""},
{"l":"marola/ledger/MlflowRunLedger$.html#","e":false,"i":"","n":"MlflowRunLedger","t":"MlflowRunLedger","d":"marola.ledger","k":"object","x":""},
{"l":"marola/llm.html#","e":false,"i":"","n":"marola.llm","t":"marola.llm","d":"","k":"package","x":""},
{"l":"marola/llm/LocalLlmClient$.html#","e":false,"i":"","n":"LocalLlmClient","t":"LocalLlmClient","d":"marola.llm","k":"object","x":""},
{"l":"marola/llm/LocalLlmClient$.html#DefaultBaseUrl-0","e":false,"i":"","n":"DefaultBaseUrl","t":"DefaultBaseUrl: String","d":"marola.llm.LocalLlmClient","k":"val","x":""},
{"l":"marola/llm/LocalLlmClient$.html#DefaultModel-0","e":false,"i":"","n":"DefaultModel","t":"DefaultModel: String","d":"marola.llm.LocalLlmClient","k":"val","x":""},
{"l":"marola/llm/LocalLlmClient.html#","e":false,"i":"","n":"LocalLlmClient","t":"LocalLlmClient(baseUrl: String, model: String) extends LlmClient","d":"marola.llm","k":"class","x":""},
{"l":"marola/llm/LocalLlmClient.html#complete-fffff1e5","e":false,"i":"","n":"complete","t":"complete(messages: List[ChatMessage]): String < Sync","d":"marola.llm.LocalLlmClient","k":"def","x":""},
{"l":"marola/observability.html#","e":false,"i":"","n":"marola.observability","t":"marola.observability","d":"","k":"package","x":""},
{"l":"marola/observability/MlflowTracing.html#","e":false,"i":"","n":"MlflowTracing","t":"MlflowTracing extends Tracing","d":"marola.observability","k":"class","x":""},
{"l":"marola/observability/MlflowTracing.html#withSpan-4a5","e":false,"i":"","n":"withSpan","t":"withSpan[A, S](name: String, attributes: Map[String, String])(effect: A < (Sync & S)): A < (Sync & S)","d":"marola.observability.MlflowTracing","k":"def","x":""},
{"l":"marola/observability/MlflowTracing$.html#","e":false,"i":"","n":"MlflowTracing","t":"MlflowTracing","d":"marola.observability","k":"object","x":""},
{"l":"marola/observability/MlflowTracing$.html#apply-fffff85d","e":false,"i":"","n":"apply","t":"apply(trackingUri: String, experimentPrefix: String): MlflowTracing < Sync","d":"marola.observability.MlflowTracing","k":"def","x":""},
{"l":"marola/observability/MlflowTracing$.html#experimentName-fffff2ca","e":false,"i":"","n":"experimentName","t":"experimentName(prefix: String): String","d":"marola.observability.MlflowTracing","k":"def","x":""},
{"l":"marola/observability/MlflowTracing$.html#headers-acd","e":false,"i":"","n":"headers","t":"headers(experimentId: String): Map[String, String]","d":"marola.observability.MlflowTracing","k":"def","x":""},
{"l":"marola/observability/MlflowTracing$.html#tracesEndpoint-fffff2ca","e":false,"i":"","n":"tracesEndpoint","t":"tracesEndpoint(trackingUri: String): String","d":"marola.observability.MlflowTracing","k":"def","x":""},
{"l":"marola/observability/MlflowTracing$.html#withExporter-fffff421","e":false,"i":"","n":"withExporter","t":"withExporter(exporter: SpanExporter): MlflowTracing","d":"marola.observability.MlflowTracing","k":"def","x":""},
{"l":"marola/sightings.html#","e":false,"i":"","n":"marola.sightings","t":"marola.sightings","d":"","k":"package","x":""},
{"l":"marola/sightings/LocalFileSightingStore$.html#","e":false,"i":"","n":"LocalFileSightingStore","t":"LocalFileSightingStore","d":"marola.sightings","k":"object","x":""},
{"l":"marola/sightings/LocalFileSightingStore$.html#DefaultPath-0","e":false,"i":"","n":"DefaultPath","t":"DefaultPath: String","d":"marola.sightings.LocalFileSightingStore","k":"val","x":""},
{"l":"marola/sightings/LocalFileSightingStore.html#","e":false,"i":"","n":"LocalFileSightingStore","t":"LocalFileSightingStore(path: String) extends SightingStore","d":"marola.sightings","k":"class","x":""},
{"l":"marola/sightings/LocalFileSightingStore.html#recentFor-ff5","e":false,"i":"","n":"recentFor","t":"recentFor(beachName: String, limit: Int): List[Sighting] < Sync","d":"marola.sightings.LocalFileSightingStore","k":"def","x":""},
{"l":"marola/sightings/LocalFileSightingStore.html#record-9c0","e":false,"i":"","n":"record","t":"record(sighting: Sighting): Unit < Sync","d":"marola.sightings.LocalFileSightingStore","k":"def","x":""},
{"l":"marola/vision.html#","e":false,"i":"","n":"marola.vision","t":"marola.vision","d":"","k":"package","x":""},
{"l":"marola/vision/LocalVisionClient$.html#","e":false,"i":"","n":"LocalVisionClient","t":"LocalVisionClient","d":"marola.vision","k":"object","x":""},
{"l":"marola/vision/LocalVisionClient$.html#DefaultModel-0","e":false,"i":"","n":"DefaultModel","t":"DefaultModel: String","d":"marola.vision.LocalVisionClient","k":"val","x":""},
{"l":"marola/vision/LocalVisionClient.html#","e":false,"i":"","n":"LocalVisionClient","t":"LocalVisionClient(baseUrl: String, model: String) extends VisionClient","d":"marola.vision","k":"class","x":""},
{"l":"marola/vision/LocalVisionClient.html#describe-fffffdc5","e":false,"i":"","n":"describe","t":"describe(imageBytes: Array[Byte]): String < Sync","d":"marola.vision.LocalVisionClient","k":"def","x":""},
{"l":"marola/water.html#","e":false,"i":"","n":"marola.water","t":"marola.water","d":"","k":"package","x":""},
{"l":"marola/water/CachedWaterQualityClient$.html#","e":false,"i":"","n":"CachedWaterQualityClient","t":"CachedWaterQualityClient","d":"marola.water","k":"object","x":""},
{"l":"marola/water/CachedWaterQualityClient$.html#decode-c47","e":false,"i":"","n":"decode","t":"decode(json: JsonValue): List[SamplingPoint]","d":"marola.water.CachedWaterQualityClient","k":"def","x":""},
{"l":"marola/water/CachedWaterQualityClient$.html#encode-599","e":false,"i":"","n":"encode","t":"encode(points: List[SamplingPoint]): JsonValue","d":"marola.water.CachedWaterQualityClient","k":"def","x":""},
{"l":"marola/water/CachedWaterQualityClient$.html#fileFor-fffff187","e":false,"i":"","n":"fileFor","t":"fileFor(dir: Path, providerName: String): Path","d":"marola.water.CachedWaterQualityClient","k":"def","x":""},
{"l":"marola/water/CachedWaterQualityClient$.html#read-fffff2e1","e":false,"i":"","n":"read","t":"read(file: Path): List[SamplingPoint]","d":"marola.water.CachedWaterQualityClient","k":"def","x":""},
{"l":"marola/water/CachedWaterQualityClient$.html#write-6ed","e":false,"i":"","n":"write","t":"write(file: Path, points: List[SamplingPoint]): Unit","d":"marola.water.CachedWaterQualityClient","k":"def","x":""},
{"l":"marola/water/CachedWaterQualityClient.html#","e":false,"i":"","n":"CachedWaterQualityClient","t":"CachedWaterQualityClient(inner: WaterQualityClient, cacheFile: Path) extends WaterQualityClient","d":"marola.water","k":"class","x":""},
{"l":"marola/water/CachedWaterQualityClient.html#name-0","e":false,"i":"","n":"name","t":"name: String","d":"marola.water.CachedWaterQualityClient","k":"def","x":""},
{"l":"marola/water/CachedWaterQualityClient.html#samplingPoints-0","e":false,"i":"","n":"samplingPoints","t":"samplingPoints: List[SamplingPoint] < Sync","d":"marola.water.CachedWaterQualityClient","k":"def","x":""},
{"l":"marola/water/FallbackWaterQualityClient$.html#","e":false,"i":"","n":"FallbackWaterQualityClient","t":"FallbackWaterQualityClient","d":"marola.water","k":"object","x":""},
{"l":"marola/water/FallbackWaterQualityClient.html#","e":false,"i":"","n":"FallbackWaterQualityClient","t":"FallbackWaterQualityClient(primary: WaterQualityClient, backup: WaterQualityClient) extends WaterQualityClient","d":"marola.water","k":"class","x":""},
{"l":"marola/water/FallbackWaterQualityClient.html#name-0","e":false,"i":"","n":"name","t":"name: String","d":"marola.water.FallbackWaterQualityClient","k":"def","x":""},
{"l":"marola/water/FallbackWaterQualityClient.html#samplingPoints-0","e":false,"i":"","n":"samplingPoints","t":"samplingPoints: List[SamplingPoint] < Sync","d":"marola.water.FallbackWaterQualityClient","k":"def","x":""},
{"l":"marola/water/ImaScPdfWaterQualityClient.html#","e":false,"i":"","n":"ImaScPdfWaterQualityClient","t":"ImaScPdfWaterQualityClient(indexUrl: String = ..., pointsUrl: String = ...) extends WaterQualityClient","d":"marola.water","k":"class","x":""},
{"l":"marola/water/ImaScPdfWaterQualityClient.html#name-0","e":false,"i":"","n":"name","t":"name: String","d":"marola.water.ImaScPdfWaterQualityClient","k":"def","x":""},
{"l":"marola/water/ImaScPdfWaterQualityClient.html#samplingPoints-0","e":false,"i":"","n":"samplingPoints","t":"samplingPoints: List[SamplingPoint] < Sync","d":"marola.water.ImaScPdfWaterQualityClient","k":"def","x":""},
{"l":"marola/water/ImaScPdfWaterQualityClient$.html#","e":false,"i":"","n":"ImaScPdfWaterQualityClient","t":"ImaScPdfWaterQualityClient","d":"marola.water","k":"object","x":""},
{"l":"marola/water/ImaScPdfWaterQualityClient$.html#DefaultIndexUrl-0","e":false,"i":"","n":"DefaultIndexUrl","t":"DefaultIndexUrl: String","d":"marola.water.ImaScPdfWaterQualityClient","k":"val","x":""},
{"l":"marola/water/ImaScPdfWaterQualityClient$.html#DefaultPointsUrl-0","e":false,"i":"","n":"DefaultPointsUrl","t":"DefaultPointsUrl: String","d":"marola.water.ImaScPdfWaterQualityClient","k":"val","x":""},
{"l":"marola/water/ImaScPdfWaterQualityClient$.html#join-399","e":false,"i":"","n":"join","t":"join(rows: List[Row], pointsJson: JsonValue): List[SamplingPoint]","d":"marola.water.ImaScPdfWaterQualityClient","k":"def","x":""},
{"l":"marola/water/ImaScPdfWaterQualityClient$.html#latestBulletinUrl-fffffd22","e":false,"i":"","n":"latestBulletinUrl","t":"latestBulletinUrl(indexHtml: String): Option[String]","d":"marola.water.ImaScPdfWaterQualityClient","k":"def","x":""},
{"l":"marola/water/ImaScWaterQualityClient$.html#","e":false,"i":"","n":"ImaScWaterQualityClient","t":"ImaScWaterQualityClient","d":"marola.water","k":"object","x":""},
{"l":"marola/water/ImaScWaterQualityClient$.html#DefaultEndpoint-0","e":false,"i":"","n":"DefaultEndpoint","t":"DefaultEndpoint: String","d":"marola.water.ImaScWaterQualityClient","k":"val","x":""},
{"l":"marola/water/ImaScWaterQualityClient$.html#coversOrigin-372","e":false,"i":"","n":"coversOrigin","t":"coversOrigin(origin: Coordinates): Boolean","d":"marola.water.ImaScWaterQualityClient","k":"def","x":""},
{"l":"marola/water/ImaScWaterQualityClient$.html#parse-c47","e":false,"i":"","n":"parse","t":"parse(json: JsonValue): List[SamplingPoint]","d":"marola.water.ImaScWaterQualityClient","k":"def","x":""},
{"l":"marola/water/ImaScWaterQualityClient.html#","e":false,"i":"","n":"ImaScWaterQualityClient","t":"ImaScWaterQualityClient(endpoint: String = ...) extends WaterQualityClient","d":"marola.water","k":"class","x":""},
{"l":"marola/water/ImaScWaterQualityClient.html#name-0","e":false,"i":"","n":"name","t":"name: String","d":"marola.water.ImaScWaterQualityClient","k":"def","x":""},
{"l":"marola/water/ImaScWaterQualityClient.html#samplingPoints-0","e":false,"i":"","n":"samplingPoints","t":"samplingPoints: List[SamplingPoint] < Sync","d":"marola.water.ImaScWaterQualityClient","k":"def","x":""},
{"l":"marola/water/IneaPdfParser$.html#","e":false,"i":"","n":"IneaPdfParser","t":"IneaPdfParser","d":"marola.water","k":"object","x":""},
{"l":"marola/water/IneaPdfParser$.html#parseTable-de0","e":false,"i":"","n":"parseTable","t":"parseTable(pdfBytes: Array[Byte]): List[Row]","d":"marola.water.IneaPdfParser","k":"def","x":""},
{"l":"marola/water/IneaPdfParser$$Row.html#","e":false,"i":"","n":"Row","t":"Row(pointCode: String, beachName: String, location: String, category: BathingCondition)","d":"marola.water.IneaPdfParser","k":"class","x":""},
{"l":"marola/water/IneaRjWaterQualityClient.html#","e":false,"i":"","n":"IneaRjWaterQualityClient","t":"IneaRjWaterQualityClient(cityPages: List[String] = ..., today: () => LocalDate = ...) extends WaterQualityClient","d":"marola.water","k":"class","x":""},
{"l":"marola/water/IneaRjWaterQualityClient.html#name-0","e":false,"i":"","n":"name","t":"name: String","d":"marola.water.IneaRjWaterQualityClient","k":"def","x":""},
{"l":"marola/water/IneaRjWaterQualityClient.html#samplingPoints-0","e":false,"i":"","n":"samplingPoints","t":"samplingPoints: List[SamplingPoint] < Sync","d":"marola.water.IneaRjWaterQualityClient","k":"def","x":""},
{"l":"marola/water/IneaRjWaterQualityClient$.html#","e":false,"i":"","n":"IneaRjWaterQualityClient","t":"IneaRjWaterQualityClient","d":"marola.water","k":"object","x":""},
{"l":"marola/water/IneaRjWaterQualityClient$.html#CityPages-0","e":false,"i":"","n":"CityPages","t":"CityPages: List[String]","d":"marola.water.IneaRjWaterQualityClient","k":"val","x":""},
{"l":"marola/water/IneaRjWaterQualityClient$.html#bulletins-94d","e":false,"i":"","n":"bulletins","t":"bulletins(pageHtml: String): List[Bulletin]","d":"marola.water.IneaRjWaterQualityClient","k":"def","x":""},
{"l":"marola/water/IneaRjWaterQualityClient$.html#coversOrigin-372","e":false,"i":"","n":"coversOrigin","t":"coversOrigin(origin: Coordinates): Boolean","d":"marola.water.IneaRjWaterQualityClient","k":"def","x":""},
{"l":"marola/water/IneaRjWaterQualityClient$.html#toSamplingPoints-fffffe80","e":false,"i":"","n":"toSamplingPoints","t":"toSamplingPoints(pdfBytes: Array[Byte], bulletinDate: LocalDate): List[SamplingPoint]","d":"marola.water.IneaRjWaterQualityClient","k":"def","x":""},
{"l":"marola/water/IneaRjWaterQualityClient$$Bulletin.html#","e":false,"i":"","n":"Bulletin","t":"Bulletin(url: String, date: LocalDate)","d":"marola.water.IneaRjWaterQualityClient","k":"class","x":""},
{"l":"marola/water/InemaBaWaterQualityClient$.html#","e":false,"i":"","n":"InemaBaWaterQualityClient","t":"InemaBaWaterQualityClient","d":"marola.water","k":"object","x":""},
{"l":"marola/water/InemaBaWaterQualityClient$.html#ListingPage-0","e":false,"i":"","n":"ListingPage","t":"ListingPage: String","d":"marola.water.InemaBaWaterQualityClient","k":"val","x":""},
{"l":"marola/water/InemaBaWaterQualityClient$.html#bulletins-fffff048","e":false,"i":"","n":"bulletins","t":"bulletins(pageHtml: String, pageUrl: String = ...): List[Bulletin]","d":"marola.water.InemaBaWaterQualityClient","k":"def","x":""},
{"l":"marola/water/InemaBaWaterQualityClient$.html#coversOrigin-372","e":false,"i":"","n":"coversOrigin","t":"coversOrigin(origin: Coordinates): Boolean","d":"marola.water.InemaBaWaterQualityClient","k":"def","x":""},
{"l":"marola/water/InemaBaWaterQualityClient$.html#toSamplingPoints-fffffe80","e":false,"i":"","n":"toSamplingPoints","t":"toSamplingPoints(pdfBytes: Array[Byte], bulletinDate: LocalDate): List[SamplingPoint]","d":"marola.water.InemaBaWaterQualityClient","k":"def","x":""},
{"l":"marola/water/InemaBaWaterQualityClient$$Bulletin.html#","e":false,"i":"","n":"Bulletin","t":"Bulletin(url: String, date: LocalDate)","d":"marola.water.InemaBaWaterQualityClient","k":"class","x":""},
{"l":"marola/water/InemaBaWaterQualityClient.html#","e":false,"i":"","n":"InemaBaWaterQualityClient","t":"InemaBaWaterQualityClient(listingPage: String = ..., today: () => LocalDate = ...) extends WaterQualityClient","d":"marola.water","k":"class","x":""},
{"l":"marola/water/InemaBaWaterQualityClient.html#name-0","e":false,"i":"","n":"name","t":"name: String","d":"marola.water.InemaBaWaterQualityClient","k":"def","x":""},
{"l":"marola/water/InemaBaWaterQualityClient.html#samplingPoints-0","e":false,"i":"","n":"samplingPoints","t":"samplingPoints: List[SamplingPoint] < Sync","d":"marola.water.InemaBaWaterQualityClient","k":"def","x":""},
{"l":"marola/water/InemaPdfParser$.html#","e":false,"i":"","n":"InemaPdfParser","t":"InemaPdfParser","d":"marola.water","k":"object","x":""},
{"l":"marola/water/InemaPdfParser$.html#parseTable-de0","e":false,"i":"","n":"parseTable","t":"parseTable(pdfBytes: Array[Byte]): List[Row]","d":"marola.water.InemaPdfParser","k":"def","x":""},
{"l":"marola/water/InemaPdfParser$$Row.html#","e":false,"i":"","n":"Row","t":"Row(code: String, pointName: String, description: String, category: String)","d":"marola.water.InemaPdfParser","k":"class","x":""},
{"l":"marola/water/SamplingPointCoordinates$.html#","e":false,"i":"","n":"SamplingPointCoordinates","t":"SamplingPointCoordinates","d":"marola.water","k":"object","x":""},
{"l":"marola/water/SamplingPointCoordinates$.html#Bahia-0","e":false,"i":"","n":"Bahia","t":"Bahia: Map[String, Coordinates]","d":"marola.water.SamplingPointCoordinates","k":"val","x":""},
{"l":"marola/water/SamplingPointCoordinates$.html#Rio-0","e":false,"i":"","n":"Rio","t":"Rio: Map[String, Coordinates]","d":"marola.water.SamplingPointCoordinates","k":"val","x":""},
{"l":"marola/water/SamplingPointCoordinates$.html#load-acd","e":false,"i":"","n":"load","t":"load(resourceName: String): Map[String, Coordinates]","d":"marola.water.SamplingPointCoordinates","k":"def","x":""},
{"l":"marola/water/SamplingPointCoordinates$$Entry.html#","e":false,"i":"","n":"Entry","t":"Entry(code: String, beachHint: String, coordinates: Coordinates, source: String)","d":"marola.water.SamplingPointCoordinates","k":"class","x":""}];