pages = [{"l":"index.html#","e":false,"i":"","n":"marola-core","t":"marola-core","d":"","k":"static","x":""},
{"l":"marola.html#","e":false,"i":"","n":"marola","t":"marola","d":"","k":"package","x":""},
{"l":"marola/beaches.html#","e":false,"i":"","n":"marola.beaches","t":"marola.beaches","d":"","k":"package","x":""},
{"l":"marola/beaches/AccessibilityClient.html#","e":false,"i":"","n":"AccessibilityClient","t":"AccessibilityClient","d":"marola.beaches","k":"trait","x":""},
{"l":"marola/beaches/AccessibilityClient.html#near-ea8","e":false,"i":"","n":"near","t":"near(beaches: List[Beach], radiusM: Int = ...): Map[String, Facilities] < Sync","d":"marola.beaches.AccessibilityClient","k":"def","x":""},
{"l":"marola/beaches/BeachFinder$.html#","e":false,"i":"","n":"BeachFinder","t":"BeachFinder","d":"marola.beaches","k":"object","x":""},
{"l":"marola/beaches/BeachFinder$.html#Endpoints-0","e":false,"i":"","n":"Endpoints","t":"Endpoints: List[String]","d":"marola.beaches.BeachFinder","k":"val","x":""},
{"l":"marola/beaches/BeachFinder$.html#defaultSnapshotDir-0","e":false,"i":"","n":"defaultSnapshotDir","t":"defaultSnapshotDir: Option[Path]","d":"marola.beaches.BeachFinder","k":"def","x":""},
{"l":"marola/beaches/BeachFinder$.html#nearby-fffff190","e":false,"i":"","n":"nearby","t":"nearby(origin: Coordinates, radiusKm: Double = ..., limit: Int = ..., snapshots: Option[Path] = ...): List[Beach] < Sync","d":"marola.beaches.BeachFinder","k":"def","x":""},
{"l":"marola/beaches/BeachSnapshot$.html#","e":false,"i":"","n":"BeachSnapshot","t":"BeachSnapshot","d":"marola.beaches","k":"object","x":""},
{"l":"marola/beaches/BeachSnapshot$.html#decode-c47","e":false,"i":"","n":"decode","t":"decode(json: JsonValue): List[Beach]","d":"marola.beaches.BeachSnapshot","k":"def","x":""},
{"l":"marola/beaches/BeachSnapshot$.html#encode-599","e":false,"i":"","n":"encode","t":"encode(beaches: List[Beach]): JsonValue","d":"marola.beaches.BeachSnapshot","k":"def","x":""},
{"l":"marola/beaches/BeachSnapshot$.html#fileFor-5a0","e":false,"i":"","n":"fileFor","t":"fileFor(dir: Path, origin: Coordinates, radiusKm: Double, limit: Int): Path","d":"marola.beaches.BeachSnapshot","k":"def","x":""},
{"l":"marola/beaches/BeachSnapshot$.html#key-fffff225","e":false,"i":"","n":"key","t":"key(origin: Coordinates, radiusKm: Double, limit: Int): String","d":"marola.beaches.BeachSnapshot","k":"def","x":""},
{"l":"marola/beaches/BeachSnapshot$.html#read-fffff2e1","e":false,"i":"","n":"read","t":"read(file: Path): List[Beach]","d":"marola.beaches.BeachSnapshot","k":"def","x":""},
{"l":"marola/beaches/BeachSnapshot$.html#write-6ed","e":false,"i":"","n":"write","t":"write(file: Path, beaches: List[Beach]): Unit","d":"marola.beaches.BeachSnapshot","k":"def","x":""},
{"l":"marola/beaches/Facilities$.html#","e":false,"i":"","n":"Facilities","t":"Facilities","d":"marola.beaches","k":"object","x":""},
{"l":"marola/beaches/Facilities$.html#NoData-0","e":false,"i":"","n":"NoData","t":"NoData: Facilities","d":"marola.beaches.Facilities","k":"val","x":""},
{"l":"marola/beaches/Facilities$.html#derived$CanEqual-0","e":false,"i":"","n":"derived$CanEqual","t":"derived$CanEqual: CanEqual[Facilities, Facilities]","d":"marola.beaches.Facilities","k":"given","x":""},
{"l":"marola/beaches/Facilities.html#","e":false,"i":"","n":"Facilities","t":"Facilities(counts: Map[Facility, Int])","d":"marola.beaches","k":"class","x":""},
{"l":"marola/beaches/Facility.html#","e":false,"i":"","n":"Facility","t":"Facility","d":"marola.beaches","k":"enum","x":""},
{"l":"marola/beaches/Facility.html#Parking-0","e":false,"i":"","n":"Parking","t":"Parking extends Facility","d":"marola.beaches.Facility","k":"val","x":""},
{"l":"marola/beaches/Facility.html#Toilets-0","e":false,"i":"","n":"Toilets","t":"Toilets extends Facility","d":"marola.beaches.Facility","k":"val","x":""},
{"l":"marola/beaches/Facility.html#Shower-0","e":false,"i":"","n":"Shower","t":"Shower extends Facility","d":"marola.beaches.Facility","k":"val","x":""},
{"l":"marola/beaches/Facility.html#Lifeguard-0","e":false,"i":"","n":"Lifeguard","t":"Lifeguard extends Facility","d":"marola.beaches.Facility","k":"val","x":""},
{"l":"marola/beaches/NoopAccessibilityClient.html#","e":false,"i":"","n":"NoopAccessibilityClient","t":"NoopAccessibilityClient extends AccessibilityClient","d":"marola.beaches","k":"class","x":""},
{"l":"marola/beaches/NoopAccessibilityClient.html#near-ea8","e":false,"i":"","n":"near","t":"near(beaches: List[Beach], radiusM: Int = ...): Map[String, Facilities] < Sync","d":"marola.beaches.NoopAccessibilityClient","k":"def","x":""},
{"l":"marola/beaches/OverpassAccessibilityClient.html#","e":false,"i":"","n":"OverpassAccessibilityClient","t":"OverpassAccessibilityClient(endpoint: String = ...) extends AccessibilityClient","d":"marola.beaches","k":"class","x":""},
{"l":"marola/beaches/OverpassAccessibilityClient.html#near-ea8","e":false,"i":"","n":"near","t":"near(beaches: List[Beach], radiusM: Int = ...): Map[String, Facilities] < Sync","d":"marola.beaches.OverpassAccessibilityClient","k":"def","x":""},
{"l":"marola/beaches/OverpassAccessibilityClient$.html#","e":false,"i":"","n":"OverpassAccessibilityClient","t":"OverpassAccessibilityClient","d":"marola.beaches","k":"object","x":""},
{"l":"marola/beaches/OverpassAccessibilityClient$.html#OverpassEndpoint-0","e":false,"i":"","n":"OverpassEndpoint","t":"OverpassEndpoint: String","d":"marola.beaches.OverpassAccessibilityClient","k":"val","x":""},
{"l":"marola/conditions.html#","e":false,"i":"","n":"marola.conditions","t":"marola.conditions","d":"","k":"package","x":""},
{"l":"marola/conditions/OpenMeteoClient$.html#","e":false,"i":"","n":"OpenMeteoClient","t":"OpenMeteoClient","d":"marola.conditions","k":"object","x":""},
{"l":"marola/conditions/OpenMeteoClient$.html#forecastFor-f24","e":false,"i":"","n":"forecastFor","t":"forecastFor(beach: Beach, forecastDays: Int = ...): BeachForecast < Sync","d":"marola.conditions.OpenMeteoClient","k":"def","x":""},
{"l":"marola/conditions/TideEvent.html#","e":false,"i":"","n":"TideEvent","t":"TideEvent(time: LocalDateTime, heightM: Double, isHigh: Boolean)","d":"marola.conditions","k":"class","x":""},
{"l":"marola/conditions/Tides$.html#","e":false,"i":"","n":"Tides","t":"Tides","d":"marola.conditions","k":"object","x":""},
{"l":"marola/conditions/Tides$.html#MinRangeM-0","e":false,"i":"","n":"MinRangeM","t":"MinRangeM: Double","d":"marola.conditions.Tides","k":"val","x":""},
{"l":"marola/conditions/Tides$.html#extrema-5c0","e":false,"i":"","n":"extrema","t":"extrema(hours: List[HourlyConditions]): List[TideEvent]","d":"marola.conditions.Tides","k":"def","x":""},
{"l":"marola/http.html#","e":false,"i":"","n":"marola.http","t":"marola.http","d":"","k":"package","x":""},
{"l":"marola/http/Http$.html#","e":false,"i":"","n":"Http","t":"Http","d":"marola.http","k":"object","x":""},
{"l":"marola/http/Http$.html#RetryableStatuses-0","e":false,"i":"","n":"RetryableStatuses","t":"RetryableStatuses: Set[Int]","d":"marola.http.Http","k":"val","x":""},
{"l":"marola/http/Http$.html#getBytes-9fc","e":false,"i":"","n":"getBytes","t":"getBytes(url: String, timeoutSeconds: Long = ...): Array[Byte] < Sync","d":"marola.http.Http","k":"def","x":""},
{"l":"marola/http/Http$.html#getString-e51","e":false,"i":"","n":"getString","t":"getString(url: String, headers: Map[String, String] = ..., retries: Int = ..., backoffMs: Long = ...): String < Sync","d":"marola.http.Http","k":"def","x":""},
{"l":"marola/http/Http$.html#postBytes-c7b","e":false,"i":"","n":"postBytes","t":"postBytes(url: String, body: Array[Byte], contentType: String = ..., headers: Map[String, String] = ..., timeoutSeconds: Long = ...): String < Sync","d":"marola.http.Http","k":"def","x":""},
{"l":"marola/http/Http$.html#postForm-5cd","e":false,"i":"","n":"postForm","t":"postForm(url: String, form: Map[String, String], timeoutSeconds: Long = ..., retries: Int = ..., backoffMs: Long = ...): String < Sync","d":"marola.http.Http","k":"def","x":""},
{"l":"marola/http/Http$.html#postJson-5c9","e":false,"i":"","n":"postJson","t":"postJson(url: String, jsonBody: String, headers: Map[String, String] = ..., timeoutSeconds: Long = ...): String < Sync","d":"marola.http.Http","k":"def","x":""},
{"l":"marola/http/Http$.html#putBytes-c7b","e":false,"i":"","n":"putBytes","t":"putBytes(url: String, body: Array[Byte], contentType: String = ..., headers: Map[String, String] = ..., timeoutSeconds: Long = ...): String < Sync","d":"marola.http.Http","k":"def","x":""},
{"l":"marola/http/Http$.html#withBinaryTransport-fffffabc","e":false,"i":"","n":"withBinaryTransport","t":"withBinaryTransport[A](t: BinaryTransport)(body: => A): A","d":"marola.http.Http","k":"def","x":""},
{"l":"marola/http/Http$.html#withTransport-fffff45b","e":false,"i":"","n":"withTransport","t":"withTransport[A](t: Transport)(body: => A): A","d":"marola.http.Http","k":"def","x":""},
{"l":"marola/http/Http$$BinaryTransport$.html#","e":false,"i":"","n":"BinaryTransport","t":"BinaryTransport","d":"marola.http.Http","k":"object","x":""},
{"l":"marola/http/Http$$BinaryTransport$.html#Live-0","e":false,"i":"","n":"Live","t":"Live: BinaryTransport","d":"marola.http.Http.BinaryTransport","k":"val","x":""},
{"l":"marola/http/Http$$BinaryTransport.html#","e":false,"i":"","n":"BinaryTransport","t":"BinaryTransport","d":"marola.http.Http","k":"trait","x":""},
{"l":"marola/http/Http$$BinaryTransport.html#send-19e","e":false,"i":"","n":"send","t":"send(request: HttpRequest): BytesResponse","d":"marola.http.Http.BinaryTransport","k":"def","x":""},
{"l":"marola/http/Http$$BytesResponse.html#","e":false,"i":"","n":"BytesResponse","t":"BytesResponse(status: Int, bytes: Array[Byte])","d":"marola.http.Http","k":"class","x":""},
{"l":"marola/http/Http$$HttpBytesError.html#","e":false,"i":"","n":"HttpBytesError","t":"HttpBytesError(status: Int, url: String) extends Exception","d":"marola.http.Http","k":"class","x":""},
{"l":"marola/http/Http$$HttpError.html#","e":false,"i":"","n":"HttpError","t":"HttpError(status: Int, url: String, bodySnippet: String) extends Exception","d":"marola.http.Http","k":"class","x":""},
{"l":"marola/http/Http$$Response.html#","e":false,"i":"","n":"Response","t":"Response(status: Int, body: String)","d":"marola.http.Http","k":"class","x":""},
{"l":"marola/http/Http$$Transport$.html#","e":false,"i":"","n":"Transport","t":"Transport","d":"marola.http.Http","k":"object","x":""},
{"l":"marola/http/Http$$Transport$.html#Live-0","e":false,"i":"","n":"Live","t":"Live: Transport","d":"marola.http.Http.Transport","k":"val","x":""},
{"l":"marola/http/Http$$Transport.html#","e":false,"i":"","n":"Transport","t":"Transport","d":"marola.http.Http","k":"trait","x":""},
{"l":"marola/http/Http$$Transport.html#send-52f","e":false,"i":"","n":"send","t":"send(request: HttpRequest): Response","d":"marola.http.Http.Transport","k":"def","x":""},
{"l":"marola/json.html#","e":false,"i":"","n":"marola.json","t":"marola.json","d":"","k":"package","x":""},
{"l":"marola/json/JsonValue.html#","e":false,"i":"","n":"JsonValue","t":"JsonValue","d":"marola.json","k":"enum","x":""},
{"l":"marola/json/JsonValue$$JObject.html#","e":false,"i":"","n":"JObject","t":"JObject(fields: Map[String, JsonValue])","d":"marola.json.JsonValue","k":"class","x":""},
{"l":"marola/json/JsonValue$$JArray.html#","e":false,"i":"","n":"JArray","t":"JArray(items: Vector[JsonValue])","d":"marola.json.JsonValue","k":"class","x":""},
{"l":"marola/json/JsonValue$$JString.html#","e":false,"i":"","n":"JString","t":"JString(value: String)","d":"marola.json.JsonValue","k":"class","x":""},
{"l":"marola/json/JsonValue$$JNumber.html#","e":false,"i":"","n":"JNumber","t":"JNumber(value: Double)","d":"marola.json.JsonValue","k":"class","x":""},
{"l":"marola/json/JsonValue$$JBool.html#","e":false,"i":"","n":"JBool","t":"JBool(value: Boolean)","d":"marola.json.JsonValue","k":"class","x":""},
{"l":"marola/json/JsonValue.html#JNull-0","e":false,"i":"","n":"JNull","t":"JNull extends JsonValue","d":"marola.json.JsonValue","k":"val","x":""},
{"l":"marola/json/JsonValue$$JObject.html#","e":false,"i":"","n":"JObject","t":"JObject(fields: Map[String, JsonValue])","d":"marola.json.JsonValue","k":"class","x":""},
{"l":"marola/json/JsonValue$$JArray.html#","e":false,"i":"","n":"JArray","t":"JArray(items: Vector[JsonValue])","d":"marola.json.JsonValue","k":"class","x":""},
{"l":"marola/json/JsonValue$$JString.html#","e":false,"i":"","n":"JString","t":"JString(value: String)","d":"marola.json.JsonValue","k":"class","x":""},
{"l":"marola/json/JsonValue$$JNumber.html#","e":false,"i":"","n":"JNumber","t":"JNumber(value: Double)","d":"marola.json.JsonValue","k":"class","x":""},
{"l":"marola/json/JsonValue$$JBool.html#","e":false,"i":"","n":"JBool","t":"JBool(value: Boolean)","d":"marola.json.JsonValue","k":"class","x":""},
{"l":"marola/json/JsonValue$.html#","e":false,"i":"","n":"JsonValue","t":"JsonValue","d":"marola.json","k":"object","x":""},
{"l":"marola/json/JsonValue$.html#arr-960","e":false,"i":"","n":"arr","t":"arr(items: JsonValue*): JsonValue","d":"marola.json.JsonValue","k":"def","x":""},
{"l":"marola/json/JsonValue$.html#bool-ffffff4b","e":false,"i":"","n":"bool","t":"bool(value: Boolean): JsonValue","d":"marola.json.JsonValue","k":"def","x":""},
{"l":"marola/json/JsonValue$.html#derived$CanEqual-0","e":false,"i":"","n":"derived$CanEqual","t":"derived$CanEqual: CanEqual[JsonValue, JsonValue]","d":"marola.json.JsonValue","k":"given","x":""},
{"l":"marola/json/JsonValue$.html#num-ab2","e":false,"i":"","n":"num","t":"num(value: Double): JsonValue","d":"marola.json.JsonValue","k":"def","x":""},
{"l":"marola/json/JsonValue$.html#obj-960","e":false,"i":"","n":"obj","t":"obj(fields: (String, JsonValue)*): JsonValue","d":"marola.json.JsonValue","k":"def","x":""},
{"l":"marola/json/JsonValue$.html#parse-566","e":false,"i":"","n":"parse","t":"parse(input: String): JsonValue","d":"marola.json.JsonValue","k":"def","x":""},
{"l":"marola/json/JsonValue$.html#str-566","e":false,"i":"","n":"str","t":"str(value: String): JsonValue","d":"marola.json.JsonValue","k":"def","x":""},
{"l":"marola/json/JsonValue$$JsonParseException.html#","e":false,"i":"","n":"JsonParseException","t":"JsonParseException(message: String) extends Exception","d":"marola.json.JsonValue","k":"class","x":""},
{"l":"marola/knowledge.html#","e":false,"i":"","n":"marola.knowledge","t":"marola.knowledge","d":"","k":"package","x":""},
{"l":"marola/knowledge/Corpus$.html#","e":false,"i":"","n":"Corpus","t":"Corpus","d":"marola.knowledge","k":"object","x":""},
{"l":"marola/knowledge/Corpus$.html#MaxChunkChars-0","e":false,"i":"","n":"MaxChunkChars","t":"MaxChunkChars: Int","d":"marola.knowledge.Corpus","k":"val","x":""},
{"l":"marola/knowledge/Corpus$.html#chunkDocument-fffffbd7","e":false,"i":"","n":"chunkDocument","t":"chunkDocument(markdown: String, safety: Boolean = ...): List[CorpusChunk]","d":"marola.knowledge.Corpus","k":"def","x":""},
{"l":"marola/knowledge/Corpus$.html#cosine-479","e":false,"i":"","n":"cosine","t":"cosine(a: Vector[Double], b: Vector[Double]): Double","d":"marola.knowledge.Corpus","k":"def","x":""},
{"l":"marola/knowledge/Corpus$.html#listFiles-fffff2e1","e":false,"i":"","n":"listFiles","t":"listFiles(dir: Path): List[Path]","d":"marola.knowledge.Corpus","k":"def","x":""},
{"l":"marola/knowledge/Corpus$.html#load-fffff6e4","e":false,"i":"","n":"load","t":"load(dir: Path): List[CorpusChunk] < Sync","d":"marola.knowledge.Corpus","k":"def","x":""},
{"l":"marola/knowledge/CorpusChunk.html#","e":false,"i":"","n":"CorpusChunk","t":"CorpusChunk(docTitle: String, source: String, text: String, safety: Boolean = ...)","d":"marola.knowledge","k":"class","x":""},
{"l":"marola/knowledge/Embedder.html#","e":false,"i":"","n":"Embedder","t":"Embedder","d":"marola.knowledge","k":"trait","x":""},
{"l":"marola/knowledge/Embedder.html#embed-fffff1e5","e":false,"i":"","n":"embed","t":"embed(texts: List[String]): List[Vector[Double]] < Sync","d":"marola.knowledge.Embedder","k":"def","x":""},
{"l":"marola/knowledge/Embedder.html#model-0","e":false,"i":"","n":"model","t":"model: String","d":"marola.knowledge.Embedder","k":"def","x":""},
{"l":"marola/knowledge/FileKnowledgeStore$.html#","e":false,"i":"","n":"FileKnowledgeStore","t":"FileKnowledgeStore","d":"marola.knowledge","k":"object","x":""},
{"l":"marola/knowledge/FileKnowledgeStore$.html#DefaultCorpusDir-0","e":false,"i":"","n":"DefaultCorpusDir","t":"DefaultCorpusDir: String","d":"marola.knowledge.FileKnowledgeStore","k":"val","x":""},
{"l":"marola/knowledge/FileKnowledgeStore$.html#DefaultIndexPath-0","e":false,"i":"","n":"DefaultIndexPath","t":"DefaultIndexPath: String","d":"marola.knowledge.FileKnowledgeStore","k":"val","x":""},
{"l":"marola/knowledge/FileKnowledgeStore.html#","e":false,"i":"","n":"FileKnowledgeStore","t":"FileKnowledgeStore(corpusDir: String, indexPath: String, embedder: Embedder) extends KnowledgeStore","d":"marola.knowledge","k":"class","x":""},
{"l":"marola/knowledge/FileKnowledgeStore.html#rebuild-0","e":false,"i":"","n":"rebuild","t":"rebuild: Int < Sync","d":"marola.knowledge.FileKnowledgeStore","k":"def","x":""},
{"l":"marola/knowledge/FileKnowledgeStore.html#search-ff5","e":false,"i":"","n":"search","t":"search(query: String, k: Int = ...): List[Passage] < Sync","d":"marola.knowledge.FileKnowledgeStore","k":"def","x":""},
{"l":"marola/knowledge/KnowledgeStore.html#","e":false,"i":"","n":"KnowledgeStore","t":"KnowledgeStore","d":"marola.knowledge","k":"trait","x":""},
{"l":"marola/knowledge/KnowledgeStore.html#search-ff5","e":false,"i":"","n":"search","t":"search(query: String, k: Int = ...): List[Passage] < Sync","d":"marola.knowledge.KnowledgeStore","k":"def","x":""},
{"l":"marola/knowledge/OceanQa$.html#","e":false,"i":"","n":"OceanQa","t":"OceanQa","d":"marola.knowledge","k":"object","x":""},
{"l":"marola/knowledge/OceanQa$.html#DefaultMinScore-0","e":false,"i":"","n":"DefaultMinScore","t":"DefaultMinScore: Double","d":"marola.knowledge.OceanQa","k":"val","x":""},
{"l":"marola/knowledge/OceanQa$.html#GeneralKnowledgeLabel-0","e":false,"i":"","n":"GeneralKnowledgeLabel","t":"GeneralKnowledgeLabel: String","d":"marola.knowledge.OceanQa","k":"val","x":""},
{"l":"marola/knowledge/OceanQa$.html#NoAnswerSentinel-0","e":false,"i":"","n":"NoAnswerSentinel","t":"NoAnswerSentinel: String","d":"marola.knowledge.OceanQa","k":"val","x":""},
{"l":"marola/knowledge/OceanQa$.html#NoPassagesReply-0","e":false,"i":"","n":"NoPassagesReply","t":"NoPassagesReply: String","d":"marola.knowledge.OceanQa","k":"val","x":""},
{"l":"marola/knowledge/OceanQa$.html#answer-2f0","e":false,"i":"","n":"answer","t":"answer(question: String, store: KnowledgeStore, llm: LlmClient, k: Int = ..., fallback: Fallback = ..., minScore: Double = ...): Answer < Sync","d":"marola.knowledge.OceanQa","k":"def","x":""},
{"l":"marola/knowledge/OceanQa$.html#buildMessages-fffff965","e":false,"i":"","n":"buildMessages","t":"buildMessages(question: String, passages: List[Passage]): List[ChatMessage]","d":"marola.knowledge.OceanQa","k":"def","x":""},
{"l":"marola/knowledge/OceanQa$.html#generalMessages-94d","e":false,"i":"","n":"generalMessages","t":"generalMessages(question: String): List[ChatMessage]","d":"marola.knowledge.OceanQa","k":"def","x":""},
{"l":"marola/knowledge/OceanQa$.html#saysNoAnswer-fffffd1b","e":false,"i":"","n":"saysNoAnswer","t":"saysNoAnswer(reply: String): Boolean","d":"marola.knowledge.OceanQa","k":"def","x":""},
{"l":"marola/knowledge/OceanQa$$Answer.html#","e":false,"i":"","n":"Answer","t":"Answer(text: String, passages: List[Passage], safety: Boolean)","d":"marola.knowledge.OceanQa","k":"class","x":""},
{"l":"marola/knowledge/OceanQa$$Fallback.html#","e":false,"i":"","n":"Fallback","t":"Fallback","d":"marola.knowledge.OceanQa","k":"enum","x":""},
{"l":"marola/knowledge/OceanQa$$Fallback.html#Strict-0","e":false,"i":"","n":"Strict","t":"Strict extends Fallback","d":"marola.knowledge.OceanQa.Fallback","k":"val","x":""},
{"l":"marola/knowledge/OceanQa$$Fallback.html#General-0","e":false,"i":"","n":"General","t":"General extends Fallback","d":"marola.knowledge.OceanQa.Fallback","k":"val","x":""},
{"l":"marola/knowledge/Passage.html#","e":false,"i":"","n":"Passage","t":"Passage(docTitle: String, source: String, text: String, score: Double, safety: Boolean = ...)","d":"marola.knowledge","k":"class","x":""},
{"l":"marola/knowledge/SafetyFooter$.html#","e":false,"i":"","n":"SafetyFooter","t":"SafetyFooter","d":"marola.knowledge","k":"object","x":""},
{"l":"marola/knowledge/SafetyFooter$.html#append-2c7","e":false,"i":"","n":"append","t":"append(text: String, safety: Boolean, lang: Lang = ...): String","d":"marola.knowledge.SafetyFooter","k":"def","x":""},
{"l":"marola/knowledge/SafetyFooter$.html#render-7c2","e":false,"i":"","n":"render","t":"render(lang: Lang): String","d":"marola.knowledge.SafetyFooter","k":"def","x":""},
{"l":"marola/knowledge/SafetyFooter$$Lang.html#","e":false,"i":"","n":"Lang","t":"Lang","d":"marola.knowledge.SafetyFooter","k":"enum","x":""},
{"l":"marola/knowledge/SafetyFooter$$Lang.html#PtBr-0","e":false,"i":"","n":"PtBr","t":"PtBr extends Lang","d":"marola.knowledge.SafetyFooter.Lang","k":"val","x":""},
{"l":"marola/knowledge/SafetyFooter$$Lang.html#En-0","e":false,"i":"","n":"En","t":"En extends Lang","d":"marola.knowledge.SafetyFooter.Lang","k":"val","x":""},
{"l":"marola/ledger.html#","e":false,"i":"","n":"marola.ledger","t":"marola.ledger","d":"","k":"package","x":""},
{"l":"marola/ledger/RunLedger$.html#","e":false,"i":"","n":"RunLedger","t":"RunLedger","d":"marola.ledger","k":"object","x":""},
{"l":"marola/ledger/RunLedger$.html#Noop-0","e":false,"i":"","n":"Noop","t":"Noop: RunLedger","d":"marola.ledger.RunLedger","k":"val","x":""},
{"l":"marola/ledger/RunLedger$$RunHandle.html#","e":false,"i":"","n":"RunHandle","t":"RunHandle(experimentId: String, runId: String, url: Option[String])","d":"marola.ledger.RunLedger","k":"class","x":""},
{"l":"marola/ledger/RunLedger.html#","e":false,"i":"","n":"RunLedger","t":"RunLedger","d":"marola.ledger","k":"trait","x":""},
{"l":"marola/ledger/RunLedger.html#artifact-fffff6d6","e":false,"i":"","n":"artifact","t":"artifact(run: RunHandle, path: Path): Unit < Sync","d":"marola.ledger.RunLedger","k":"def","x":""},
{"l":"marola/ledger/RunLedger.html#end-fffff1c1","e":false,"i":"","n":"end","t":"end(run: RunHandle, ok: Boolean): Unit < Sync","d":"marola.ledger.RunLedger","k":"def","x":""},
{"l":"marola/ledger/RunLedger.html#metrics-ffffffe0","e":false,"i":"","n":"metrics","t":"metrics(run: RunHandle, values: Map[String, Double], step: Int = ...): Unit < Sync","d":"marola.ledger.RunLedger","k":"def","x":""},
{"l":"marola/ledger/RunLedger.html#start-fffffe05","e":false,"i":"","n":"start","t":"start(experiment: String, name: String, params: Map[String, String]): RunHandle < Sync","d":"marola.ledger.RunLedger","k":"def","x":""},
{"l":"marola/llm.html#","e":false,"i":"","n":"marola.llm","t":"marola.llm","d":"","k":"package","x":""},
{"l":"marola/llm/ChatMessage.html#","e":false,"i":"","n":"ChatMessage","t":"ChatMessage(role: String, content: String)","d":"marola.llm","k":"class","x":""},
{"l":"marola/llm/CompiledPrompt.html#","e":false,"i":"","n":"CompiledPrompt","t":"CompiledPrompt(instructions: String, demos: List[Map[String, String]], outputField: String)","d":"marola.llm","k":"class","x":""},
{"l":"marola/llm/CompiledPrompt.html#buildMessages-fffff42a","e":false,"i":"","n":"buildMessages","t":"buildMessages(inputs: Map[String, String]): List[ChatMessage]","d":"marola.llm.CompiledPrompt","k":"def","x":""},
{"l":"marola/llm/CompiledPrompt$.html#","e":false,"i":"","n":"CompiledPrompt","t":"CompiledPrompt","d":"marola.llm","k":"object","x":""},
{"l":"marola/llm/CompiledPrompt$.html#loadFromString-1f4","e":false,"i":"","n":"loadFromString","t":"loadFromString(jsonText: String, outputField: String): CompiledPrompt","d":"marola.llm.CompiledPrompt","k":"def","x":""},
{"l":"marola/llm/LlmClient.html#","e":false,"i":"","n":"LlmClient","t":"LlmClient","d":"marola.llm","k":"trait","x":""},
{"l":"marola/llm/LlmClient.html#complete-fffff1e5","e":false,"i":"","n":"complete","t":"complete(messages: List[ChatMessage]): String < Sync","d":"marola.llm.LlmClient","k":"def","x":""},
{"l":"marola/llm/LlmClient$.html#","e":false,"i":"","n":"LlmClient","t":"LlmClient","d":"marola.llm","k":"object","x":""},
{"l":"marola/llm/LlmClient$.html#extractContent-fffff2ca","e":false,"i":"","n":"extractContent","t":"extractContent(responseBody: String): String","d":"marola.llm.LlmClient","k":"def","x":""},
{"l":"marola/llm/LlmClient$$NoCompletionException.html#","e":false,"i":"","n":"NoCompletionException","t":"NoCompletionException(message: String) extends Exception","d":"marola.llm.LlmClient","k":"class","x":""},
{"l":"marola/llm/Reviewer$.html#","e":false,"i":"","n":"Reviewer","t":"Reviewer","d":"marola.llm","k":"object","x":""},
{"l":"marola/llm/Reviewer$.html#review-1ef","e":false,"i":"","n":"review","t":"review(client: LlmClient, prompt: CompiledPrompt, factInputs: Map[String, String], draftSummary: String): ReviewResult < Sync","d":"marola.llm.Reviewer","k":"def","x":""},
{"l":"marola/llm/Reviewer$$MalformedReviewException.html#","e":false,"i":"","n":"MalformedReviewException","t":"MalformedReviewException(message: String) extends Exception","d":"marola.llm.Reviewer","k":"class","x":""},
{"l":"marola/llm/Reviewer$$ReviewResult.html#","e":false,"i":"","n":"ReviewResult","t":"ReviewResult(finalSummary: String, score: Int, verdict: String)","d":"marola.llm.Reviewer","k":"class","x":""},
{"l":"marola/llm/TracedLlmClient$.html#","e":false,"i":"","n":"TracedLlmClient","t":"TracedLlmClient","d":"marola.llm","k":"object","x":""},
{"l":"marola/llm/TracedLlmClient$.html#contentFromEnv-c43","e":false,"i":"","n":"contentFromEnv","t":"contentFromEnv(value: Option[String]): Boolean","d":"marola.llm.TracedLlmClient","k":"def","x":""},
{"l":"marola/llm/TracedLlmClient$.html#renderPrompt-fffffeb7","e":false,"i":"","n":"renderPrompt","t":"renderPrompt(messages: List[ChatMessage]): String","d":"marola.llm.TracedLlmClient","k":"def","x":""},
{"l":"marola/llm/TracedLlmClient.html#","e":false,"i":"","n":"TracedLlmClient","t":"TracedLlmClient(inner: LlmClient, model: String, tracing: Tracing, traceContent: Boolean) extends LlmClient","d":"marola.llm","k":"class","x":""},
{"l":"marola/llm/TracedLlmClient.html#complete-fffff1e5","e":false,"i":"","n":"complete","t":"complete(messages: List[ChatMessage]): String < Sync","d":"marola.llm.TracedLlmClient","k":"def","x":""},
{"l":"marola/location.html#","e":false,"i":"","n":"marola.location","t":"marola.location","d":"","k":"package","x":""},
{"l":"marola/location/IpGeolocation$.html#","e":false,"i":"","n":"IpGeolocation","t":"IpGeolocation","d":"marola.location","k":"object","x":""},
{"l":"marola/location/IpGeolocation$.html#AgreementRadiusKm-0","e":false,"i":"","n":"AgreementRadiusKm","t":"AgreementRadiusKm: Double","d":"marola.location.IpGeolocation","k":"val","x":""},
{"l":"marola/location/IpGeolocation$.html#Providers-0","e":false,"i":"","n":"Providers","t":"Providers: List[Provider]","d":"marola.location.IpGeolocation","k":"val","x":""},
{"l":"marola/location/IpGeolocation$.html#consensus-fffff78f","e":false,"i":"","n":"consensus","t":"consensus(candidates: List[(String, Coordinates, Option[String])]): Option[IpLocation]","d":"marola.location.IpGeolocation","k":"def","x":""},
{"l":"marola/location/IpGeolocation$.html#locate-0","e":false,"i":"","n":"locate","t":"locate: Option[IpLocation] < Sync","d":"marola.location.IpGeolocation","k":"def","x":""},
{"l":"marola/location/IpGeolocation$$Provider.html#","e":false,"i":"","n":"Provider","t":"Provider(name: String, url: String, parse: JsonValue => Option[(Coordinates, Option[String])])","d":"marola.location.IpGeolocation","k":"class","x":""},
{"l":"marola/location/IpLocation.html#","e":false,"i":"","n":"IpLocation","t":"IpLocation(coordinates: Coordinates, city: Option[String], agreeingSources: List[String], totalSources: Int)","d":"marola.location","k":"class","x":""},
{"l":"marola/log.html#","e":false,"i":"","n":"marola.log","t":"marola.log","d":"","k":"package","x":""},
{"l":"marola/log/Log.html#","e":false,"i":"","n":"Log","t":"Log(underlying: Logger)","d":"marola.log","k":"class","x":""},
{"l":"marola/log/Log.html#debug-571","e":false,"i":"","n":"debug","t":"debug(inline message: String): Unit","d":"marola.log.Log","k":"def","x":""},
{"l":"marola/log/Log.html#error-571","e":false,"i":"","n":"error","t":"error(inline message: String): Unit","d":"marola.log.Log","k":"def","x":""},
{"l":"marola/log/Log.html#info-571","e":false,"i":"","n":"info","t":"info(inline message: String): Unit","d":"marola.log.Log","k":"def","x":""},
{"l":"marola/log/Log.html#warn-571","e":false,"i":"","n":"warn","t":"warn(inline message: String): Unit","d":"marola.log.Log","k":"def","x":""},
{"l":"marola/log/Log$.html#","e":false,"i":"","n":"Log","t":"Log","d":"marola.log","k":"object","x":""},
{"l":"marola/log/Log$.html#forName-537","e":false,"i":"","n":"forName","t":"forName(name: String): Log","d":"marola.log.Log","k":"def","x":""},
{"l":"marola/lore.html#","e":false,"i":"","n":"marola.lore","t":"marola.lore","d":"","k":"package","x":""},
{"l":"marola/lore/LoreEntry.html#","e":false,"i":"","n":"LoreEntry","t":"LoreEntry(id: String, kind: LoreKind, text: String, source: String, regions: Set[String], months: Option[Set[Int]], lang: String)","d":"marola.lore","k":"class","x":""},
{"l":"marola/lore/LoreKind.html#","e":false,"i":"","n":"LoreKind","t":"LoreKind","d":"marola.lore","k":"enum","x":""},
{"l":"marola/lore/LoreKind.html#Secret-0","e":false,"i":"","n":"Secret","t":"Secret extends LoreKind","d":"marola.lore.LoreKind","k":"val","x":""},
{"l":"marola/lore/LoreKind.html#Creature-0","e":false,"i":"","n":"Creature","t":"Creature extends LoreKind","d":"marola.lore.LoreKind","k":"val","x":""},
{"l":"marola/lore/SeaLore$.html#","e":false,"i":"","n":"SeaLore","t":"SeaLore","d":"marola.lore","k":"object","x":""},
{"l":"marola/lore/SeaLore$.html#DefaultResource-0","e":false,"i":"","n":"DefaultResource","t":"DefaultResource: String","d":"marola.lore.SeaLore","k":"val","x":""},
{"l":"marola/lore/SeaLore$.html#format-f51","e":false,"i":"","n":"format","t":"format(entry: LoreEntry): String","d":"marola.lore.SeaLore","k":"def","x":""},
{"l":"marola/lore/SeaLore$.html#loadDefault-fffffc52","e":false,"i":"","n":"loadDefault","t":"loadDefault(): List[LoreEntry]","d":"marola.lore.SeaLore","k":"def","x":""},
{"l":"marola/lore/SeaLore$.html#parse-94d","e":false,"i":"","n":"parse","t":"parse(jsonText: String): List[LoreEntry]","d":"marola.lore.SeaLore","k":"def","x":""},
{"l":"marola/lore/SeaLore$.html#pick-fffff482","e":false,"i":"","n":"pick","t":"pick(entries: List[LoreEntry], today: LocalDate, beachName: String, regions: Set[String]): Option[LoreEntry]","d":"marola.lore.SeaLore","k":"def","x":""},
{"l":"marola/lore/SeaLore$.html#regionTagsFor-fffff45c","e":false,"i":"","n":"regionTagsFor","t":"regionTagsFor(origin: Coordinates): Set[String]","d":"marola.lore.SeaLore","k":"def","x":""},
{"l":"marola/model.html#","e":false,"i":"","n":"marola.model","t":"marola.model","d":"","k":"package","x":""},
{"l":"marola/model/Beach.html#","e":false,"i":"","n":"Beach","t":"Beach(name: String, coordinates: Coordinates, distanceKm: Double)","d":"marola.model","k":"class","x":""},
{"l":"marola/model/BeachForecast.html#","e":false,"i":"","n":"BeachForecast","t":"BeachForecast(beach: Beach, timezoneId: String, hours: List[HourlyConditions])","d":"marola.model","k":"class","x":""},
{"l":"marola/model/BestHour.html#","e":false,"i":"","n":"BestHour","t":"BestHour(beach: Beach, hour: HourlyConditions, score: Int, jellyfishRisk: JellyfishRisk, whaleSightingLikelihood: WhaleSightingLikelihood, notes: List[Note], waterQuality: Option[WaterQuality] = ..., dayTides: List[TideEvent] = ..., whalePeak: Option[HourlyConditions] = ..., facilities: Facilities = ...)","d":"marola.model","k":"class","x":""},
{"l":"marola/model/Coordinates$.html#","e":false,"i":"","n":"Coordinates","t":"Coordinates","d":"marola.model","k":"object","x":""},
{"l":"marola/model/Coordinates$.html#fromMapsUrl-fffffd22","e":false,"i":"","n":"fromMapsUrl","t":"fromMapsUrl(url: String): Option[Coordinates]","d":"marola.model.Coordinates","k":"def","x":""},
{"l":"marola/model/Coordinates.html#","e":false,"i":"","n":"Coordinates","t":"Coordinates(lat: Double, lon: Double)","d":"marola.model","k":"class","x":""},
{"l":"marola/model/Coordinates.html#distanceKm-fffff347","e":false,"i":"","n":"distanceKm","t":"distanceKm(other: Coordinates): Double","d":"marola.model.Coordinates","k":"def","x":""},
{"l":"marola/model/HourlyConditions.html#","e":false,"i":"","n":"HourlyConditions","t":"HourlyConditions(time: LocalDateTime, airTempC: Option[Double], seaTempC: Option[Double], waveHeightM: Option[Double], windSpeedKmh: Option[Double], windDirectionDeg: Option[Double], currentVelocityKmh: Option[Double], uvIndex: Option[Double], precipitationProbabilityPct: Option[Double], isDaylight: Option[Boolean], wavePeriodS: Option[Double] = ..., waveDirectionDeg: Option[Double] = ..., swellWaveHeightM: Option[Double] = ..., swellWavePeriodS: Option[Double] = ..., seaLevelM: Option[Double] = ...)","d":"marola.model","k":"class","x":""},
{"l":"marola/model/JellyfishRisk.html#","e":false,"i":"","n":"JellyfishRisk","t":"JellyfishRisk","d":"marola.model","k":"enum","x":""},
{"l":"marola/model/JellyfishRisk.html#Low-0","e":false,"i":"","n":"Low","t":"Low extends JellyfishRisk","d":"marola.model.JellyfishRisk","k":"val","x":""},
{"l":"marola/model/JellyfishRisk.html#Moderate-0","e":false,"i":"","n":"Moderate","t":"Moderate extends JellyfishRisk","d":"marola.model.JellyfishRisk","k":"val","x":""},
{"l":"marola/model/JellyfishRisk.html#High-0","e":false,"i":"","n":"High","t":"High extends JellyfishRisk","d":"marola.model.JellyfishRisk","k":"val","x":""},
{"l":"marola/model/WhaleSightingLikelihood.html#","e":false,"i":"","n":"WhaleSightingLikelihood","t":"WhaleSightingLikelihood","d":"marola.model","k":"enum","x":""},
{"l":"marola/model/WhaleSightingLikelihood.html#Low-0","e":false,"i":"","n":"Low","t":"Low extends WhaleSightingLikelihood","d":"marola.model.WhaleSightingLikelihood","k":"val","x":""},
{"l":"marola/model/WhaleSightingLikelihood.html#Moderate-0","e":false,"i":"","n":"Moderate","t":"Moderate extends WhaleSightingLikelihood","d":"marola.model.WhaleSightingLikelihood","k":"val","x":""},
{"l":"marola/model/WhaleSightingLikelihood.html#High-0","e":false,"i":"","n":"High","t":"High extends WhaleSightingLikelihood","d":"marola.model.WhaleSightingLikelihood","k":"val","x":""},
{"l":"marola/model/WindLevel.html#","e":false,"i":"","n":"WindLevel","t":"WindLevel","d":"marola.model","k":"enum","x":""},
{"l":"marola/model/WindLevel.html#Calm-0","e":false,"i":"","n":"Calm","t":"Calm extends WindLevel","d":"marola.model.WindLevel","k":"val","x":""},
{"l":"marola/model/WindLevel.html#Breezy-0","e":false,"i":"","n":"Breezy","t":"Breezy extends WindLevel","d":"marola.model.WindLevel","k":"val","x":""},
{"l":"marola/model/WindLevel.html#Strong-0","e":false,"i":"","n":"Strong","t":"Strong extends WindLevel","d":"marola.model.WindLevel","k":"val","x":""},
{"l":"marola/observability.html#","e":false,"i":"","n":"marola.observability","t":"marola.observability","d":"","k":"package","x":""},
{"l":"marola/observability/Tracing.html#","e":false,"i":"","n":"Tracing","t":"Tracing","d":"marola.observability","k":"trait","x":""},
{"l":"marola/observability/Tracing.html#llmSpan-fffffad2","e":false,"i":"","n":"llmSpan","t":"llmSpan[A, S](model: String, attributes: Map[String, String])(effect: A < (Sync & S))(result: A => Map[String, String]): A < (Sync & S)","d":"marola.observability.Tracing","k":"def","x":""},
{"l":"marola/observability/Tracing.html#withSpan-4a5","e":false,"i":"","n":"withSpan","t":"withSpan[A, S](name: String, attributes: Map[String, String] = ...)(effect: A < (Sync & S)): A < (Sync & S)","d":"marola.observability.Tracing","k":"def","x":""},
{"l":"marola/observability/Tracing$.html#","e":false,"i":"","n":"Tracing","t":"Tracing","d":"marola.observability","k":"object","x":""},
{"l":"marola/observability/Tracing$$Noop$.html#","e":false,"i":"","n":"Noop","t":"Noop extends Tracing","d":"marola.observability.Tracing","k":"object","x":""},
{"l":"marola/observability/Tracing$$Noop$.html#withSpan-4a5","e":false,"i":"","n":"withSpan","t":"withSpan[A, S](name: String, attributes: Map[String, String])(effect: A < (Sync & S)): A < (Sync & S)","d":"marola.observability.Tracing.Noop","k":"def","x":""},
{"l":"marola/scoring.html#","e":false,"i":"","n":"marola.scoring","t":"marola.scoring","d":"","k":"package","x":""},
{"l":"marola/scoring/Note.html#","e":false,"i":"","n":"Note","t":"Note(code: NoteCode, args: Map[String, JsonValue] = ...)","d":"marola.scoring","k":"class","x":""},
{"l":"marola/scoring/Note.html#english-0","e":false,"i":"","n":"english","t":"english: String","d":"marola.scoring.Note","k":"def","x":""},
{"l":"marola/scoring/Note.html#json-0","e":false,"i":"","n":"json","t":"json: JsonValue","d":"marola.scoring.Note","k":"def","x":""},
{"l":"marola/scoring/Note$.html#","e":false,"i":"","n":"Note","t":"Note","d":"marola.scoring","k":"object","x":""},
{"l":"marola/scoring/Note$.html#derived$CanEqual-0","e":false,"i":"","n":"derived$CanEqual","t":"derived$CanEqual: CanEqual[Note, Note]","d":"marola.scoring.Note","k":"given","x":""},
{"l":"marola/scoring/NoteCode$.html#","e":false,"i":"","n":"NoteCode","t":"NoteCode","d":"marola.scoring","k":"object","x":""},
{"l":"marola/scoring/NoteCode$.html#derived$CanEqual-0","e":false,"i":"","n":"derived$CanEqual","t":"derived$CanEqual: CanEqual[NoteCode, NoteCode]","d":"marola.scoring.NoteCode","k":"given","x":""},
{"l":"marola/scoring/NoteCode$.html#fromLabel-fffffd22","e":false,"i":"","n":"fromLabel","t":"fromLabel(label: String): Option[NoteCode]","d":"marola.scoring.NoteCode","k":"def","x":""},
{"l":"marola/scoring/NoteCode.html#","e":false,"i":"","n":"NoteCode","t":"NoteCode(val label: String)","d":"marola.scoring","k":"enum","x":""},
{"l":"marola/scoring/NoteCode.html#RoughSeas-0","e":false,"i":"","n":"RoughSeas","t":"RoughSeas extends NoteCode","d":"marola.scoring.NoteCode","k":"val","x":""},
{"l":"marola/scoring/NoteCode.html#Choppy-0","e":false,"i":"","n":"Choppy","t":"Choppy extends NoteCode","d":"marola.scoring.NoteCode","k":"val","x":""},
{"l":"marola/scoring/NoteCode.html#NoWaveData-0","e":false,"i":"","n":"NoWaveData","t":"NoWaveData extends NoteCode","d":"marola.scoring.NoteCode","k":"val","x":""},
{"l":"marola/scoring/NoteCode.html#StrongWind-0","e":false,"i":"","n":"StrongWind","t":"StrongWind extends NoteCode","d":"marola.scoring.NoteCode","k":"val","x":""},
{"l":"marola/scoring/NoteCode.html#Breezy-0","e":false,"i":"","n":"Breezy","t":"Breezy extends NoteCode","d":"marola.scoring.NoteCode","k":"val","x":""},
{"l":"marola/scoring/NoteCode.html#NoWindData-0","e":false,"i":"","n":"NoWindData","t":"NoWindData extends NoteCode","d":"marola.scoring.NoteCode","k":"val","x":""},
{"l":"marola/scoring/NoteCode.html#ColdWater-0","e":false,"i":"","n":"ColdWater","t":"ColdWater extends NoteCode","d":"marola.scoring.NoteCode","k":"val","x":""},
{"l":"marola/scoring/NoteCode.html#WarmWater-0","e":false,"i":"","n":"WarmWater","t":"WarmWater extends NoteCode","d":"marola.scoring.NoteCode","k":"val","x":""},
{"l":"marola/scoring/NoteCode.html#NoSeaTempData-0","e":false,"i":"","n":"NoSeaTempData","t":"NoSeaTempData extends NoteCode","d":"marola.scoring.NoteCode","k":"val","x":""},
{"l":"marola/scoring/NoteCode.html#RainLikely-0","e":false,"i":"","n":"RainLikely","t":"RainLikely extends NoteCode","d":"marola.scoring.NoteCode","k":"val","x":""},
{"l":"marola/scoring/NoteCode.html#Dark-0","e":false,"i":"","n":"Dark","t":"Dark extends NoteCode","d":"marola.scoring.NoteCode","k":"val","x":""},
{"l":"marola/scoring/NoteCode.html#JellyfishElevated-0","e":false,"i":"","n":"JellyfishElevated","t":"JellyfishElevated extends NoteCode","d":"marola.scoring.NoteCode","k":"val","x":""},
{"l":"marola/scoring/NoteCode.html#JellyfishSome-0","e":false,"i":"","n":"JellyfishSome","t":"JellyfishSome extends NoteCode","d":"marola.scoring.NoteCode","k":"val","x":""},
{"l":"marola/scoring/NoteCode.html#WaterStale-0","e":false,"i":"","n":"WaterStale","t":"WaterStale extends NoteCode","d":"marola.scoring.NoteCode","k":"val","x":""},
{"l":"marola/scoring/NoteCode.html#WaterUnfit-0","e":false,"i":"","n":"WaterUnfit","t":"WaterUnfit extends NoteCode","d":"marola.scoring.NoteCode","k":"val","x":""},
{"l":"marola/scoring/NoteCode.html#WaterMixed-0","e":false,"i":"","n":"WaterMixed","t":"WaterMixed extends NoteCode","d":"marola.scoring.NoteCode","k":"val","x":""},
{"l":"marola/scoring/Swimability$.html#","e":false,"i":"","n":"Swimability","t":"Swimability","d":"marola.scoring","k":"object","x":""},
{"l":"marola/scoring/Swimability$.html#hourPreference-fffff4b1","e":false,"i":"","n":"hourPreference","t":"hourPreference(hour: HourlyConditions): Int","d":"marola.scoring.Swimability","k":"def","x":""},
{"l":"marola/scoring/Swimability$.html#isWhaleSeason-d0f","e":false,"i":"","n":"isWhaleSeason","t":"isWhaleSeason(time: LocalDateTime): Boolean","d":"marola.scoring.Swimability","k":"def","x":""},
{"l":"marola/scoring/Swimability$.html#jellyfishRisk-fffff6ce","e":false,"i":"","n":"jellyfishRisk","t":"jellyfishRisk(hour: HourlyConditions): JellyfishRisk","d":"marola.scoring.Swimability","k":"def","x":""},
{"l":"marola/scoring/Swimability$.html#score-845","e":false,"i":"","n":"score","t":"score(hour: HourlyConditions, water: WaterVerdict = ...): (Int, List[Note])","d":"marola.scoring.Swimability","k":"def","x":""},
{"l":"marola/scoring/Swimability$.html#waterVerdict-fffff282","e":false,"i":"","n":"waterVerdict","t":"waterVerdict(water: Option[WaterQuality], today: LocalDate): WaterVerdict","d":"marola.scoring.Swimability","k":"def","x":""},
{"l":"marola/scoring/Swimability$.html#whaleSightingLikelihood-fffff2e7","e":false,"i":"","n":"whaleSightingLikelihood","t":"whaleSightingLikelihood(hour: HourlyConditions): WhaleSightingLikelihood","d":"marola.scoring.Swimability","k":"def","x":""},
{"l":"marola/scoring/Swimability$.html#windLevel-fffff8fa","e":false,"i":"","n":"windLevel","t":"windLevel(kmh: Option[Double]): Option[WindLevel]","d":"marola.scoring.Swimability","k":"def","x":""},
{"l":"marola/scoring/WaterVerdict$.html#","e":false,"i":"","n":"WaterVerdict","t":"WaterVerdict","d":"marola.scoring","k":"object","x":""},
{"l":"marola/scoring/WaterVerdict$.html#NoData-0","e":false,"i":"","n":"NoData","t":"NoData: WaterVerdict","d":"marola.scoring.WaterVerdict","k":"val","x":""},
{"l":"marola/scoring/WaterVerdict.html#","e":false,"i":"","n":"WaterVerdict","t":"WaterVerdict(delta: Int, veto: Boolean, note: Option[Note], summary: String)","d":"marola.scoring","k":"class","x":""},
{"l":"marola/sightings.html#","e":false,"i":"","n":"marola.sightings","t":"marola.sightings","d":"","k":"package","x":""},
{"l":"marola/sightings/Sighting.html#","e":false,"i":"","n":"Sighting","t":"Sighting(beachName: String, kind: SightingKind, note: Option[String], reportedAt: Instant)","d":"marola.sightings","k":"class","x":""},
{"l":"marola/sightings/SightingKind.html#","e":false,"i":"","n":"SightingKind","t":"SightingKind","d":"marola.sightings","k":"enum","x":""},
{"l":"marola/sightings/SightingKind.html#Jellyfish-0","e":false,"i":"","n":"Jellyfish","t":"Jellyfish extends SightingKind","d":"marola.sightings.SightingKind","k":"val","x":""},
{"l":"marola/sightings/SightingKind.html#Whale-0","e":false,"i":"","n":"Whale","t":"Whale extends SightingKind","d":"marola.sightings.SightingKind","k":"val","x":""},
{"l":"marola/sightings/SightingKind.html#Pollution-0","e":false,"i":"","n":"Pollution","t":"Pollution extends SightingKind","d":"marola.sightings.SightingKind","k":"val","x":""},
{"l":"marola/sightings/SightingStore.html#","e":false,"i":"","n":"SightingStore","t":"SightingStore","d":"marola.sightings","k":"trait","x":""},
{"l":"marola/sightings/SightingStore.html#recentFor-ff5","e":false,"i":"","n":"recentFor","t":"recentFor(beachName: String, limit: Int = ...): List[Sighting] < Sync","d":"marola.sightings.SightingStore","k":"def","x":""},
{"l":"marola/sightings/SightingStore.html#record-9c0","e":false,"i":"","n":"record","t":"record(sighting: Sighting): Unit < Sync","d":"marola.sightings.SightingStore","k":"def","x":""},
{"l":"marola/site.html#","e":false,"i":"","n":"marola.site","t":"marola.site","d":"","k":"package","x":""},
{"l":"marola/site/Board$.html#","e":false,"i":"","n":"Board","t":"Board","d":"marola.site","k":"object","x":""},
{"l":"marola/site/Board$.html#SchemaVersion-0","e":false,"i":"","n":"SchemaVersion","t":"SchemaVersion: Int","d":"marola.site.Board","k":"val","x":""},
{"l":"marola/site/Board$.html#build-3c7","e":false,"i":"","n":"build","t":"build(area: String, day: LocalDate, today: LocalDate, generatedAt: OffsetDateTime, scored: List[BestHour], lore: Option[LoreEntry], sources: Sources, trails: List[Trail] = ...): JsonValue","d":"marola.site.Board","k":"def","x":""},
{"l":"marola/site/Board$.html#stamp-d48","e":false,"i":"","n":"stamp","t":"stamp(t: OffsetDateTime): String","d":"marola.site.Board","k":"def","x":""},
{"l":"marola/site/Board$$Sources.html#","e":false,"i":"","n":"Sources","t":"Sources(beaches: String, forecast: String, water: Option[String])","d":"marola.site.Board","k":"class","x":""},
{"l":"marola/trails.html#","e":false,"i":"","n":"marola.trails","t":"marola.trails","d":"","k":"package","x":""},
{"l":"marola/trails/Trail.html#","e":false,"i":"","n":"Trail","t":"Trail(name: String, lengthKm: Double, difficulty: Option[String], surface: Option[String], geometry: List[Coordinates], nearBeach: Option[(String, Double)], nearLake: Option[(String, Double)])","d":"marola.trails","k":"class","x":""},
{"l":"marola/trails/TrailFinder$.html#","e":false,"i":"","n":"TrailFinder","t":"TrailFinder","d":"marola.trails","k":"object","x":""},
{"l":"marola/trails/TrailFinder$.html#NearRadiusKm-0","e":false,"i":"","n":"NearRadiusKm","t":"NearRadiusKm: Double","d":"marola.trails.TrailFinder","k":"val","x":""},
{"l":"marola/trails/TrailFinder$.html#nearby-fffff3be","e":false,"i":"","n":"nearby","t":"nearby(origin: Coordinates, radiusKm: Double, beaches: List[Beach]): List[Trail] < Sync","d":"marola.trails.TrailFinder","k":"def","x":""},
{"l":"marola/trails/TrailFinder$.html#nearbyOrEmpty-fffff3be","e":false,"i":"","n":"nearbyOrEmpty","t":"nearbyOrEmpty(origin: Coordinates, radiusKm: Double, beaches: List[Beach]): List[Trail] < Sync","d":"marola.trails.TrailFinder","k":"def","x":""},
{"l":"marola/vision.html#","e":false,"i":"","n":"marola.vision","t":"marola.vision","d":"","k":"package","x":""},
{"l":"marola/vision/VisionClient.html#","e":false,"i":"","n":"VisionClient","t":"VisionClient","d":"marola.vision","k":"trait","x":""},
{"l":"marola/vision/VisionClient.html#describe-fffffdc5","e":false,"i":"","n":"describe","t":"describe(imageBytes: Array[Byte]): String < Sync","d":"marola.vision.VisionClient","k":"def","x":""},
{"l":"marola/water.html#","e":false,"i":"","n":"marola.water","t":"marola.water","d":"","k":"package","x":""},
{"l":"marola/water/BathingCondition$.html#","e":false,"i":"","n":"BathingCondition","t":"BathingCondition","d":"marola.water","k":"object","x":""},
{"l":"marola/water/BathingCondition$.html#derived$CanEqual-0","e":false,"i":"","n":"derived$CanEqual","t":"derived$CanEqual: CanEqual[BathingCondition, BathingCondition]","d":"marola.water.BathingCondition","k":"given","x":""},
{"l":"marola/water/BathingCondition$.html#fromLabel-fffffd22","e":false,"i":"","n":"fromLabel","t":"fromLabel(s: String): Option[BathingCondition]","d":"marola.water.BathingCondition","k":"def","x":""},
{"l":"marola/water/BathingCondition$.html#label-930","e":false,"i":"extension (c: BathingCondition)","n":"label","t":"label: String","d":"marola.water.BathingCondition","k":"def","x":""},
{"l":"marola/water/BathingCondition.html#","e":false,"i":"","n":"BathingCondition","t":"BathingCondition","d":"marola.water","k":"enum","x":""},
{"l":"marola/water/BathingCondition.html#Proper-0","e":false,"i":"","n":"Proper","t":"Proper extends BathingCondition","d":"marola.water.BathingCondition","k":"val","x":""},
{"l":"marola/water/BathingCondition.html#Improper-0","e":false,"i":"","n":"Improper","t":"Improper extends BathingCondition","d":"marola.water.BathingCondition","k":"val","x":""},
{"l":"marola/water/BathingCondition.html#Unknown-0","e":false,"i":"","n":"Unknown","t":"Unknown extends BathingCondition","d":"marola.water.BathingCondition","k":"val","x":""},
{"l":"marola/water/SamplingPoint.html#","e":false,"i":"","n":"SamplingPoint","t":"SamplingPoint(id: String, beachName: String, pointName: String, location: String, coordinates: Coordinates, samples: List[WaterSample])","d":"marola.water","k":"class","x":""},
{"l":"marola/water/SamplingPoint.html#latest-0","e":false,"i":"","n":"latest","t":"latest: Option[WaterSample]","d":"marola.water.SamplingPoint","k":"def","x":""},
{"l":"marola/water/WaterQuality.html#","e":false,"i":"","n":"WaterQuality","t":"WaterQuality(points: List[SamplingPoint], source: String)","d":"marola.water","k":"class","x":""},
{"l":"marola/water/WaterQuality.html#fresh-fffff6ce","e":false,"i":"","n":"fresh","t":"fresh(today: LocalDate): List[(SamplingPoint, WaterSample)]","d":"marola.water.WaterQuality","k":"def","x":""},
{"l":"marola/water/WaterQuality.html#improper-fffff6ce","e":false,"i":"","n":"improper","t":"improper(today: LocalDate): List[(SamplingPoint, WaterSample)]","d":"marola.water.WaterQuality","k":"def","x":""},
{"l":"marola/water/WaterQuality.html#latestSamples-0","e":false,"i":"","n":"latestSamples","t":"latestSamples: List[(SamplingPoint, WaterSample)]","d":"marola.water.WaterQuality","k":"def","x":""},
{"l":"marola/water/WaterQuality.html#newestSampleDate-0","e":false,"i":"","n":"newestSampleDate","t":"newestSampleDate: Option[LocalDate]","d":"marola.water.WaterQuality","k":"def","x":""},
{"l":"marola/water/WaterQuality$.html#","e":false,"i":"","n":"WaterQuality","t":"WaterQuality","d":"marola.water","k":"object","x":""},
{"l":"marola/water/WaterQuality$.html#MaxSampleAgeDays-0","e":false,"i":"","n":"MaxSampleAgeDays","t":"MaxSampleAgeDays: Long","d":"marola.water.WaterQuality","k":"val","x":""},
{"l":"marola/water/WaterQuality$.html#isFresh-fffffde0","e":false,"i":"","n":"isFresh","t":"isFresh(sampledOn: LocalDate, today: LocalDate): Boolean","d":"marola.water.WaterQuality","k":"def","x":""},
{"l":"marola/water/WaterQualityClient.html#","e":false,"i":"","n":"WaterQualityClient","t":"WaterQualityClient","d":"marola.water","k":"trait","x":""},
{"l":"marola/water/WaterQualityClient.html#name-0","e":false,"i":"","n":"name","t":"name: String","d":"marola.water.WaterQualityClient","k":"def","x":""},
{"l":"marola/water/WaterQualityClient.html#samplingPoints-0","e":false,"i":"","n":"samplingPoints","t":"samplingPoints: List[SamplingPoint] < Sync","d":"marola.water.WaterQualityClient","k":"def","x":""},
{"l":"marola/water/WaterQualityMatcher$.html#","e":false,"i":"","n":"WaterQualityMatcher","t":"WaterQualityMatcher","d":"marola.water","k":"object","x":""},
{"l":"marola/water/WaterQualityMatcher$.html#MaxDistanceKm-0","e":false,"i":"","n":"MaxDistanceKm","t":"MaxDistanceKm: Double","d":"marola.water.WaterQualityMatcher","k":"val","x":""},
{"l":"marola/water/WaterQualityMatcher$.html#assign-fffff08d","e":false,"i":"","n":"assign","t":"assign(beaches: List[Beach], points: List[SamplingPoint], source: String): Map[String, WaterQuality]","d":"marola.water.WaterQualityMatcher","k":"def","x":""},
{"l":"marola/water/WaterQualityMatcher$.html#isInlandWater-fffffd1b","e":false,"i":"","n":"isInlandWater","t":"isInlandWater(providerBeachName: String): Boolean","d":"marola.water.WaterQualityMatcher","k":"def","x":""},
{"l":"marola/water/WaterQualityMatcher$.html#namesMatch-cd6","e":false,"i":"","n":"namesMatch","t":"namesMatch(a: String, b: String): Boolean","d":"marola.water.WaterQualityMatcher","k":"def","x":""},
{"l":"marola/water/WaterQualityMatcher$.html#normalise-fffff2ca","e":false,"i":"","n":"normalise","t":"normalise(name: String): String","d":"marola.water.WaterQualityMatcher","k":"def","x":""},
{"l":"marola/water/WaterSample.html#","e":false,"i":"","n":"WaterSample","t":"WaterSample(sampledOn: LocalDate, condition: BathingCondition, rain: Option[String], enterococciPer100ml: Option[Int], waterTempC: Option[Double])","d":"marola.water","k":"class","x":""},
{"l":"marola/Recommender$.html#","e":false,"i":"","n":"Recommender","t":"Recommender","d":"marola","k":"object","x":""},
{"l":"marola/Recommender$.html#bestHoursTomorrow-fffff8c4","e":false,"i":"","n":"bestHoursTomorrow","t":"bestHoursTomorrow(origin: Coordinates, radiusKm: Double = ..., beachLimit: Int = ..., waterQuality: Option[WaterQualityClient] = ..., today: ZoneId => LocalDate = ..., accessibility: Option[AccessibilityClient] = ...): List[BestHour] < Sync","d":"marola.Recommender","k":"def","x":""},
{"l":"marola/Recommender$.html#bestPerBeachTomorrow-fffff8c4","e":false,"i":"","n":"bestPerBeachTomorrow","t":"bestPerBeachTomorrow(origin: Coordinates, radiusKm: Double = ..., beachLimit: Int = ..., waterQuality: Option[WaterQualityClient] = ..., today: ZoneId => LocalDate = ..., accessibility: Option[AccessibilityClient] = ...): List[BestHour] < Sync","d":"marola.Recommender","k":"def","x":""},
{"l":"marola/Recommender$.html#scoreDays-403","e":false,"i":"","n":"scoreDays","t":"scoreDays(origin: Coordinates, radiusKm: Double = ..., beachLimit: Int = ..., waterQuality: Option[WaterQualityClient] = ..., today: ZoneId => LocalDate = ..., days: Int = ..., accessibility: Option[AccessibilityClient] = ...): List[BestHour] < Sync","d":"marola.Recommender","k":"def","x":""}];